### ISSUE TITLE
⚡ GitHub Action Skips the Upload Step

### ISSUE THREAD

**Issue by Tanishq-Banyal** [softprops/action-gh-release#106]
I switched to action-gh-release for the multiple file upload feature but when running the workflow it just skips the upload step. I suspect it's something related to tags.

![IMG_20210523_201020](https://user-images.githubusercontent.com/68330937/119265055-f74e6a80-bc02-11eb-83ae-8dc77ae652c1.jpg)

1. Why is that ? Do I need to set some extra options ?
2. How do I create new tag and bump version number automatically on running the workflow ?

**My Yaml File :-**
```yaml
name: build-and-release
on: [workflow_dispatch]
jobs:
  build-creator:
    name: Build & Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      
      - name: Setup Java Envirionment
        uses: actions/setup-java@v2.1.0
        with:
          distribution: adopt-hotspot
          java-version: 15
      
      - name: Building with Gradle
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: 6.9
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: 'build -x lint'
      
      - name: Upload APK Files to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./app/build/outputs/apk/*/*/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

What am I doing wrong ? Please Help me.

I also tried without using glob patterns but still same result.
