### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by ericoporto** [softprops/action-gh-release#107]
Last release is from more than a year ago. GH discontinued their own GH Release actions and have at the time linked this repository as their recommendation, so this is why I am asking.

**Comment by IceflowRE** [comment]
https://github.com/ncipollo/release-action
Might be an alternative with more features.

**Comment by yin1999** [comment]
If you are looking for some action for multiple file uploading, just try [GitHub Cli](https://cli.github.com/manual/gh_release_create). It has been preinstalled in GitHub actions `Virtual Environments`.

```yaml
run: |
  gh release create ${{ env.VERSION }} -n "${{ env.MESSAGE }}" -t "${{ env.NAME }}" ${{ env.FILES }}
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSION: "tag for release"
  MESSAGE: "message for release"
  NAME: "release name"
  FILES: path/to/file1 path/to/file2 ...
```

**Comment by 2bndy5** [comment]
@yin1999 That's a good tip, but I don't like the idea of automated releases (or even having to write a manually-triggered workflow to disable the automation). For the same reason I don't let my monthly bills take money out of my bank account, I prefer to have absolute control over some seemingly vital things.

**Comment by andrewbanchich** [comment]
@2bndy5 I agree, so I modified it to:

```yaml
run: |
  gh release upload --clobber ${{ env.VERSION }} ${{ env.FILES }}
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSION: ${{ needs.draft_release.outputs.tag_name }}
  FILES: foo.txt baz.txt
```

That way I use the `release-draft` GH Action so it doesn't auto-release, and the above step will not create a release, but just upload the assets to the existing draft release.
