### ISSUE TITLE
GitHub release failed with status: 404, retrying...

### ISSUE THREAD

**Issue by rhalaly** [softprops/action-gh-release#110]
Got the error: `GitHub release failed with status: 404, retrying...`

https://github.com/rhalaly/scope-to-this-vscode/runs/2869520835?check_suite_focus=true

Running in an infinite loop. Any idea what is the reason? And how to prevent an infinite loop in the release pipeline?

**Comment by aleks-ivanov** [comment]
It happens in with `422` as well.

This should be high priority fix. Infinite loops are very detrimental in general and especially in this case, because the GitHub API calls limit is reached almost in an instant.

The problem is [here on line 232](https://github.com/softprops/action-gh-release/blob/master/src/github.ts#L232). This `return release(config, releaser);` needs to be encased in a conditional that at least checks for these two 402 and 422 statuses.

I would love to contribute that, but I don't feel at all competent enough to make it optimal.

**Comment by rhalaly** [comment]
But why the `createRelease` returns 404? A retry mechanism is important, but why it isn't working?

**Comment by aleks-ivanov** [comment]
Have you tried to create a release through the GitHub UI or CLI ?

**Comment by rhalaly** [comment]
Eventually, I created the release via GitHub UI

**Comment by aleks-ivanov** [comment]
Same with the problem I am having. 
Through the action fails, through the GitHub UI/CLI works.

According to the previous several issues, this action seems to have been left unmaintained, so I think I will be switching to CLI commands in the pipeline.

**Comment by rhalaly** [comment]
Can you please share the code of how to use the CLI directly in the pipeline? (Even though this repo is unmaintained, I will create a PR that will limit the retries)

**Comment by aleks-ivanov** [comment]
Depends on what you need specifically of course, but it should look something like this:

```
run: |
  gh release create ${{ env.VERSION }} -n "${{ env.MESSAGE }}" -t "${{ env.NAME }}" ${{ env.FILES }}
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSION: "tag for release"
  MESSAGE: "message for release"
  NAME: "release name"
  FILES: path/to/file1 path/to/file2 ...
```
The sample code is from [this thread](https://github.com/softprops/action-gh-release/issues/107#issuecomment-854700244)

When I make it specifically for the pipeline I am working on, I will share a link to it.

**Comment by rhalaly** [comment]
@aleks-ivanov Thank you! is the `gh` command predefined in the pipeline?

**Comment by aleks-ivanov** [comment]
On the GitHub Actions runners it should be pre-installed and setup on all variants.

Like this, on [the Ubuntu 20.04 runner for example](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#cli-tools).

**Comment by softprops** [comment]
> But why the createRelease returns 404 

A 404  can happen for different reasons. In a future release Im going to include more debugging information from api response headers the logs. The the mean time the next release will include a change that limits the number of api retries are made

**Comment by kxn468** [comment]
![image](https://user-images.githubusercontent.com/100859090/199324686-e545daf5-6873-4ed0-ade2-037ff3acd118.png)

having the same issue, can anyone help me out

**Comment by vitobotta** [comment]
Having this issue right now. Any suggestions?

**Comment by pF-luis** [comment]
Same problem for me

**Comment by minamisouju** [comment]
I've got same error when I use Personal Access Token to release on other repo.
```
with:
  token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
```

in my case, I need to add "Content write" permission to that token, for both repositories.
- home repository which have this GitHub Actions
- foreign repository which is destination of release

I guess this Actions create release on both home and foreign repo even if we set `repository` input, so we need permission for both.

**Comment by asaurabhW** [comment]
> ![image](https://user-images.githubusercontent.com/100859090/199324686-e545daf5-6873-4ed0-ade2-037ff3acd118.png)
> 
> having the same issue, can anyone help me out

I am also facing the same issue. I tried to give even `permissions: write-all` (only for trial), but I still face same issue. Any pointers are appreciated.

**Comment by alexrashed** [comment]
Just for the record: I was having the exact same issue with a custom token without referencing another issue. The custom token was used to have a specific user listed as the creator of the release. The workflow step looks like this:
```
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'builds/*'
          draft: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
```

In my case, the issue was caused that the personal access token used in the secret was in fact a PAT of the correct user, but did not have the right scopes assigned.

**Comment by vickvasquez** [comment]
In addition to having the correct permissions, don't forget to add the custom token in the secrets in the target repository

**Comment by multani** [comment]
For those facing this issue: [the "create release" API returns 404 if the discussion category name is invalid](https://docs.github.com/en/free-pro-team@latest/rest/releases/releases?apiVersion=2022-11-28#create-a-release).

![image](https://github.com/softprops/action-gh-release/assets/65311/419dfaca-f3d6-4b0c-babc-40583897383e)

If you are using the flag to create a discussion for the release and are getting this error, make sure:

* The discussion feature is enabled inside the repository's settings
* The related discussion category exists

**Comment by keenan-v1** [comment]
Hello.

I am having this issue now with a repository that doesn't even have discussions enabled, nor am I passing in a category to the action.

<img width="951" alt="image" src="https://github.com/softprops/action-gh-release/assets/2093265/9ff0e956-e9ac-4ce2-815e-08accd5bae4e">

Discussions are not enabled:
<img width="761" alt="image" src="https://github.com/softprops/action-gh-release/assets/2093265/a18d9bb4-0d4e-4fe8-9cc0-7a895c30eb69">

And I'm using a composite action to run this, but it has worked on three other repositories without issue.
```yaml
    - name: Create Release
      id: create-release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ inputs.github-token }}
        target_commitish: ${{ inputs.commit-sha }}
        prerelease: ${{ inputs.is-rc == 'true' }}
        make_latest: ${{ inputs.is-rc != 'true' }}
        tag_name: ${{ inputs.tag }}
        generate_release_notes: true
        files: |
          ${{ inputs.path }}/*
```

Seeing as this action hasn't been updated in the last 24 hours and the same composite action works on other repositories tested today, I'm at a loss as to what the issue may be for this one repository. Hoping someone here may have suggestions.

I have tried enabling and disabling Discussions.

Thank you.
