### ISSUE TITLE
Upload to another github repo Doesnt work:

### ISSUE THREAD

**Issue by Eliminater74** [softprops/action-gh-release#113]
Testing the option to upload to another repo, doesnt seem to work, it still defaults to current repo only.

Example of use:

```
    - name: Upload firmware to release
      uses: softprops/action-gh-release@master
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: DevOpenWRT-Router/OpenWRT_LEDE_PureFusion_Releases
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
```
