### ISSUE TITLE
Action tries to make a new release when one already exists

### ISSUE THREAD

**Issue by optix2000** [softprops/action-gh-release#140]
I use `action-gh-release` to automatically upload a CI build when a new release is cut. Recently this has stopped working. It looks like the action is trying to make the release, even though it already exists.

```yaml
release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release'}}
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: totsugeki
    - uses: softprops/action-gh-release@v1
      with:
        files: totsugeki.exe
```

https://github.com/optix2000/totsugeki/runs/3275313508?check_suite_focus=true
```
Run softprops/action-gh-release@v1
👩‍🏭 Creating new GitHub release for tag v1.1.3...
⚠️ GitHub release failed with status: 422, retrying... (2 retries remaining)
👩‍🏭 Creating new GitHub release for tag v1.1.3...
⚠️ GitHub release failed with status: 422, retrying... (1 retries remaining)
👩‍🏭 Creating new GitHub release for tag v1.1.3...
⚠️ GitHub release failed with status: 422, retrying... (0 retries remaining)
❌ Too many retries. Aborting...
Error: Too many retries.
```

Compared to previously:
https://github.com/optix2000/totsugeki/runs/3268658767?check_suite_focus=true
```
Run softprops/action-gh-release@v1
⬆️ Uploading totsugeki.exe...
Deprecation: [@octokit/rest] "file" parameter is deprecated for ".repos.uploadReleaseAsset()". Use "data" instead
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:437047
    at Array.forEach (<anonymous>)
    at Object.s [as uploadReleaseAsset] (/home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:436958)
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:52043
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:50565
    at new Promise (<anonymous>)
    at i (/home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:50313)
    at Object.t.upload (/home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:51907)
    at /home/runner/work/_actions/softprops/action-gh-release/v1/dist/index.js:1:44485 {
  name: 'Deprecation'
}
🎉 Release ready at https://github.com/optix2000/totsugeki/releases/tag/v1.1.2
```
