### ISSUE TITLE
Action is to work in v0.1.7 but get the error in the latest

### ISSUE THREAD

**Issue by Gkirito** [softprops/action-gh-release#142]
same like this
[https://github.com/softprops/action-gh-release/issues/129#issuecomment-894822810](url)

``` 
Run softprops/action-gh-release@v0.1.10
👩‍🏭 Creating new GitHub release for tag v0.0.4...
⚠️ GitHub release failed with status: 404, retrying... (2 retries remaining)
👩‍🏭 Creating new GitHub release for tag v0.0.4...
⚠️ GitHub release failed with status: 422, retrying... (1 retries remaining)
👩‍🏭 Creating new GitHub release for tag v0.0.4...
⚠️ GitHub release failed with status: 422, retrying... (0 retries remaining)
❌ Too many retries. Aborting...
Error: Too many retries.
``` 
config:
``` 
   - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist/main.js"
```
It's to work in v0.1.7 but get the error in the latest
