### ISSUE TITLE
github-actions released this x days ago

### ISSUE THREAD

**Issue by jnsmalm** [softprops/action-gh-release#148]
When creating a release, it says "github-actions released this x days ago" instead of "jnsmalm released this x days ago" (which is what I want). How can I fix this? I found another issue https://github.com/softprops/action-gh-release/issues/141 which is the same thing, were it was said it was fixed. For me it seems it still doesn't work as expected.

This is my action:

```yaml
name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Build
      run: |
        npm install
        npm run build
    - name: Test Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.js
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
```
