### ISSUE TITLE
Can not release ".app" files on macos

### ISSUE THREAD

**Issue by FlamingTuri** [softprops/action-gh-release#153]
I am trying to deploy assets for linux, windows and mac, however the action fails with the following error when trying to upload a .app artifact:

Error: invalid json response body at https://uploads.github.com/repos/FlamingTuri/test/releases/49039002/assets?name=main-macos.app reason: Unexpected token < in JSON at position 0

This is the configuration I am using, and the artifact that I am uploading are a simple python hello world created with pyinstaller

```yaml
name: release-artifacts

on: release

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifactName: main-linux
          - os: windows-latest
            artifactName: main-windows.exe
          - os: macos-latest
            artifactName: main-macos.app
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: node .github/script/release-artifacts.mjs ${{ matrix.artifactName }}
      - uses: softprops/action-gh-release@v1
        with:
          files: server/dist/${{ matrix.artifactName }}
```

Moreover, if I remove the ".app" extension the release of the three artifacts is successful, but only the linux job is completed successfully, while the macos and the windows ones fail.
