### ISSUE TITLE
With.files input doesn't work correctly when working-directory is set

### ISSUE THREAD

**Issue by kolotaev** [softprops/action-gh-release#158]
Hello,

I have a simple github workflow with a `working-directory` specified. Obviously Action doesn't take this setting into account when searching for file(s) specified in `with.files`.

Actual:
- Action reports "🤔 Pattern 'Release.txt' does not match any files." and doesn't release the file(s) specified in the input.
Expected:
- Action releases file(s) specified in the input.

Example:
```yaml
name: Some-name
on:
  push:
    branches:
    - master
jobs:
  packer-build:
    name:
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: some/directory/here
    steps:
    - name: Checkout VCS
      uses: actions/checkout@v2
    - name: Build
      run: echo ${{ github.sha }} > Release.txt
    - name: Test
      run: cat Release.txt
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: Release.txt
        tag_name: latest
```
