### ISSUE TITLE
Add option to use annotated tag message as release notes

### ISSUE THREAD

**Issue by spenserblack** [softprops/action-gh-release#162]
Annotated tags can contain release notes, and it would be nice if this action provided an option to use the tag's message as the GitHub Release notes.

**Comment by spenserblack** [comment]
Note: Looks like `git tag -l --format="%(contents:body)" <tag name>` gets the tag message.
Until this is implemented a workaround could be to write the contents to a file and use `body_path`,
or set the result as an output in a previous step.

**Comment by spenserblack** [comment]
I think I finally got the workaround working :weary:
This is an example of what I did
```yaml
name: Release
on:
  push:
    tags: ['v*.*.*']

jobs:
  release-notes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Get Release Notes
        run: 'echo "$(git tag -l --format="%(contents:body)" $GITHUB_REF_NAME)" > RELEASE_NOTES'
      - name: Set Release Notes
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE_NOTES
```
