### ISSUE TITLE
Release time does not update

### ISSUE THREAD

**Issue by emcruise** [softprops/action-gh-release#171]
## expected behaviour

I expected that when i generate a release through GitHub-Actions as such:
```yaml
on:
  push:
    branches: [ main, release-publish ]
  schedule:
    - cron: "* */6 * * *"
[...]
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: linux-latest
        files: |
          client/dist/client
```
that the release which is generated points to the commit which triggered the action and the time of the push.

## actual behaviour
The assets of the release are the correct after the workflow run, but the release points to the wrong commit and therefore states a wrong time.

## Issue in more detail

In [my project](https://github.com/emcruise/tor-rootkit) I have a cron job, which regularly updates my releases. Even though the assets change correctly the release states a wrong time and points to a wrong commit, which can be seen [here](https://github.com/emcruise/tor-rootkit/tree/c56ad74cb60eb6db5fca58468250d6800ef26ee7). The wrong time could result to me living in a UTC+1 time zone which could give my commits a wrong time, but this still doesn't explain why the release points to the wrong commit. When I delete the releases and regenerate them through GitHub-Actions they work correctly and point to the correct commit with the correct time.

**Comment by softprops** [comment]
The current behavior is to update a release when attempting to create a release of the same version. 

For something like an automated nightly release you may want a tag that reflects the date so that you can compare one release to another

**Comment by christhekeele** [comment]
Spitballing as I work through a similar workflow here, but rather than adding dates to your tags,

- Since GH derives the release date from the tag creation date
  - I think the `creatordate` from `git tag -l --sort=-creatordate --format='%(creatordate):  %(refname:short)'`
- Since the action's current behaviour makes sense in a lot of contexts
- Since the action updates the release based on tag name, without checking if the tag has changed

It seems like you could accomplish what you want by "moving" the tag (deleting and recreating it) before running the release action, ex:

```yaml
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Update release tag
        run: |
          git tag -d linux-latest
          git push origin :refs/tags/linux-latest
          git tag linux-latest
          git push origin linux-latest

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: linux-latest
          files: |
            client/dist/client
```

**Comment by 0x192** [comment]
If you follow the @christhekeele example, don't forget to add the missing `actions/checkout` before using the git command or it would fail. 

If you don't want the job to fail when the tag doesn't exist, just add `|| true` to the first 2 git commands.

Here is an extract of my workflow:

```yaml
env:
  dev_tag: dev-build

jobs:
  build:
    uses: ./.github/workflows/build_artifacts.yml
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Downloads artifacts
        uses: actions/download-artifact@v3
        with:
          path: bin
      - name: Update dev-build tag
        if: ${{ github.event_name == 'push' }}
        run: |
          git tag -d ${{ env.dev_tag }} || true
          git push origin :refs/tags/${{ env.dev_tag }} || true
          git tag ${{ env.dev_tag }}
          git push origin ${{ env.dev_tag }}
      - name: Create dev-build release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: bin/*/uad_gui-*
          prerelease: true
          tag_name: ${{ env.dev_tag }}
```

[Here is the whole workflow](https://github.com/0x192/universal-android-debloater/blob/main/.github/workflows/release.yml) if it can be useful to someone. I'm pretty happy with it
