### ISSUE TITLE
Please retry uploading when failed.

### ISSUE THREAD

**Issue by abcfy2** [softprops/action-gh-release#187]
Sometimes I will get this error https://github.com/abcfy2/aria2-static-build/runs/4349111525?check_suite_focus=true:

```
Run softprops/action-gh-release@v1
/usr/bin/docker exec  356d60f2fa6f6229b94833f4ef730b7baa9d4f62c9f0341db5214911e5c29164 sh -c "cat /etc/*release | grep ^ID"
⬆️ Uploading aria2-aarch64-linux-musl_static.zip...
Error: request to https://uploads.github.com/repos/abcfy2/aria2-static-build/releases/54209979/assets?name=aria2-aarch64-linux-musl_static.zip failed, reason: read ECONNRESET
```

Please retry when uploading failed. Thanks.

**Comment by wez** [comment]
Note that when using the GH Actions "rerun all jobs" after encountering this error, you can encounter https://github.com/softprops/action-gh-release/issues/166 instead, which requires deleting the half-uploaded files before re-running the jobs again will succeed.

**Comment by wez** [comment]
Note that when using the GH Actions "rerun all jobs" after encountering this error, you can encounter https://github.com/softprops/action-gh-release/issues/166 instead, which requires deleting the half-uploaded files before re-running the jobs again will succeed.

**Comment by wez** [comment]
https://github.com/softprops/action-gh-release/pull/181 seems relevant

**Comment by softprops** [comment]
If release assets share the same name they should be deleted when a release is reattempted https://github.com/softprops/action-gh-release/blob/58fa4b7a8863f6beaf115a49196308842b8b0f06/src/github.ts#L152

**Comment by abcfy2** [comment]
@softprops Would you please add this feature? I'm facing this issue just now.

**Comment by jonasmusall** [comment]
I am facing the same issue. Right now, I use this workaround:
```yml
steps:
  - name: Upload assets
    id: upload_try1
    continue-on-error: true
    uses: softprops/action-gh-release@v1
    with:
      files: ${{ env.RELEASE_ASSETS }}
  - name: Upload assets (retry)
    id: upload_try2
    if: steps.upload_try1.outcome == 'failure'
    continue-on-error: true
    uses: softprops/action-gh-release@v1
    with:
      files: ${{ env:RELEASE_ASSETS }}
# more retries
```
