### ISSUE TITLE
generate_release_notes

### ISSUE THREAD

**Issue by suntong** [softprops/action-gh-release#191]
The readme says on the `generate_release_notes`:

> If body is specified, the body will be pre-pended to the automatically generated notes. 

But, this is my yaml

```yaml
      - name: Upload release package
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release.outputs.name }}
          files: ./dist/*
          generate_release_notes: true
```

and I got:

https://github.com/suntong/dbab/releases/tag/1.5.8

not quite like other people's results in #179.

What I'm missing? thx!
