### ISSUE TITLE
 GitHub Releases requires a tag

### ISSUE THREAD

**Issue by preetjdp** [softprops/action-gh-release#20]
I keep getting this error that my git tag has not been set, tried multiple ways to do that from the command line and from bash inside of the action. Could not get promising results hence this issue.

Here is my main.yaml
  ```
name: Fast Builds

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'      
    - run: flutter doctor
    - run: flutter pub get
    - run: flutter build apk
    - name: Display the path
      run: |
        echo ${PATH}
        git tag 0.0.1
        echo "wow"
      shell: bash
#     -name: Debug Info
#      shell: bash
#      run: |
#         GITHUB_TAG = "0.0.1"
#         git tag ${GITHUB_TAG}
#         echo "Release Tag :   ${GITHUB_TAG}"
    - name: Release To Git
      uses: softprops/action-gh-release@v1
#       if: startsWith(github.ref, 'refs/tags/')
      with: 
        body: "A new release"
        files: build/app/outputs/apk/release/app-release.apk
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by softprops** [comment]
A few things to note

1) this action required a tag because [GitHub releases do](https://help.github.com/en/articles/creating-releases). That is not a bug.

2) The push event that triggers the workflow run needs to be the push associated with a `git push origin {tag}`. The reason being that GitHub releases can only be created if GitHub servers know about the associated tag.

It looks like the push that is triggering these runs is a push of a commit.

3) the tag operation within the workflow only exists in the workflow run checkout, not on your GitHub origin remote. If you push this within your workflow run it should trigger another run where the push is for your tag

4) environment variables export within a step are not by default exposed to future steps. This is because every step runs in its own process.

You can use a [custom command](https://help.github.com/en/articles/development-tools-for-github-actions#set-an-environment-variable-set-env) to pass env variables between workflow steps

---

I will try and follow up on this with documentation on a strategy for creating tags within a workflow run

**Comment by Amet13** [comment]
I'm also struggled with that problem, trying to fix it somehow.
Is there any hack on how to create tag automatically after creating and publishing release?
Or maybe some option to ignore tag checking (as it worked before)?

**Comment by skirpichev** [comment]
I notice same error in https://github.com/diofant/diofant/commit/6740f83761a14a06f44ab0b1d001907f70bcba0e/checks?check_suite_id=262644565
This build was initially triggered by tag push, but was unsuccessful due one of slow tests and then - was restarted.

**Comment by Alkrun** [comment]
I'm using [gitversion](https://github.com/GitTools/GitVersion) for versioning, which handles versioning based on branches... It doesn't work when checking out a tag instead of a branch so I can't use a github workflow triggered by a pushed tag.

I've currently got the following steps:

```yaml
    - name: Tag
      if: startsWith(github.ref, 'refs/heads/release/')
      run: |
        git tag "v$env:GitVersion_SemVer"
        git push origin "v$env:GitVersion_SemVer"
    - name: Release
      if: startsWith(github.ref, 'refs/heads/release/')
      uses: softprops/action-gh-release@v1
      with:
        name: v${{ env.GitVersion_SemVer }}
        prerelease: ${{ env.GitVersion_PreReleaseLabel != '' }}
        files: ./artifacts/sidekick-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Couldn't `action-gh-release` create the release based on the name I'm providing?  What additional information does it need that requires this be a pushed tag that triggered the build?

**Comment by bc3tech** [comment]
+1 to this confusion; see no reason that I can't specify a tag name and this Action tags & releases all in one go.

**Comment by proddy** [comment]
+1 same here

**Comment by roslovets** [comment]
+1

**Comment by rcdailey** [comment]
Is this still an issue? I'm triggering release process based on a pull request merge for branches prefixed with `release/`. I will want to create a tag AND github release in this workflow.

**Comment by Septias** [comment]
I guess it should work like this, right?
```bash
$ git tag 1.1.1              
$ git push origin 1.1.1   
```
Because using this I get `⚠️ GitHub Releases requires a tag`

**Comment by Septias** [comment]
![image](https://user-images.githubusercontent.com/39526136/115970557-66bd3580-a543-11eb-801f-9dcd3a1a0e7a.png)
Well I added a tag and still got that error :/
```
git tag 1.1.1
git push origin master 1.1.1
```

**Comment by roslovets** [comment]
I swithed to another action that does it easy.

**Comment by proddy** [comment]
> I swithed to another action that does it easy.

same here

**Comment by rcdailey** [comment]
> I swithed to another action that does it easy.

@roslovets If you did, please mention the name here to help others out. Thank you.

**Comment by roslovets** [comment]
> @roslovets If you did, please mention the name here to help others out. Thank you.

I use [ncipollo/release-action](https://github.com/marketplace/actions/create-release) to create release just after tagging in the same workflow. [Example](https://github.com/Roslovets-Inc/zip-npm-files/blob/a605f8ee8ab56bf7a7996d38399a50083eb00777/.github/workflows/build_and_release.yml#L99)

**Comment by windowsair** [comment]
In fact, as @softprops said, you need a tag to create a release.

Regarding what @Septias said, it still doesn't work after adding the tag, I think it may be that the tag is not pushed to github, for more discussion on this see:  [Push git commits & tags simultaneously](https://stackoverflow.com/questions/3745135/push-git-commits-tags-simultaneously)

----

This issue is basically related to `tag_name`, and here are a few ways to solve the problem.
1. Set your action to trigger only when it contains a tag
2. Specify a tag explicitly

The following example specifies a tag named "test":
```yaml
    - name: Release user files
      uses: softprops/action-gh-release@v1
      with:
        tag_name: test
        files: |
          file1
          file2
```
![image](https://user-images.githubusercontent.com/17078589/144702443-a598deb3-e20f-4ac3-852e-5acf7995d9b9.png)


Specifying a tag for each commit is annoying. As in the example given by @roslovets, you can introduce version number control for the tag. 

Another example is to specify a tag name for each nightly build version:
```yaml
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
    - name: Release user firmware
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
          file1
          file2
```

![image](https://user-images.githubusercontent.com/17078589/144702469-7b2f8cf1-cee8-4f47-bbb8-2d9e2f4f1dcb.png)

**Comment by staghouse** [comment]
Thank you for the clarity and your example approaches, https://github.com/softprops/action-gh-release/issues/20#issuecomment-985988391

**Comment by Xonshiz** [comment]
Thanks for this amazing example @windowsair .
Also, to point out for someone who will stumble on this issue... that `id: tag` is important for that section.
I didn't add it and wasted 30 minutes trying to figure out why my tag wasn't working.

**Comment by xianshenglu** [comment]
I used another action to get the previous tag
```yaml
      - name: 'Get Previous tag'
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0
      
      - name: Release        
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.previous_tag.outputs.tag}}
          files: ${{steps.sign_app.outputs.signedReleaseFile}}
```
