### ISSUE TITLE
Glob pattern with brace expansion not recognized

### ISSUE THREAD

**Issue by swissmanu** [softprops/action-gh-release#204]
Hi there. First up, thank you for the `action-gh-release` action ❤️ I like how simple it makes interactions with the GitHub Releases feature.

To my (potential) bug report: I try to upload multiple files with different file extensions to my release. As I understand, `files` supports glob patterns:

```yaml
jobs:
  bundle:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - platform: ubuntu-latest
            buildFolder: deb
            releaseAssetPattern: "*.{{deb,AppImage.tar.gz,AppImage.tar.gz.sig}}"
          - platform: macos-latest
            buildFolder: dmg
            releaseAssetPattern: "*.{{dmg,tar.gz,tar.gz.sig}}"
          - platform: windows-latest
            buildFolder: msi
            releaseAssetPattern: "*.{{msi,msi.zip,msi.zip.sig}}"
    steps:
      # ... other steps
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          fail_on_unmatched_files: true
          files: ${{ format('./src-tauri/target/release/bundle/{0}/{1}', matrix.buildFolder, matrix.releaseAssetPattern) }}
```
At execution, I get the following behavior:

<img width="758" alt="CleanShot 2022-02-02 at 14 59 58@2x" src="https://user-images.githubusercontent.com/170832/152169159-c86b60ee-6f14-46b0-8f98-ec7e650606d0.png">

It seems like `action-gh-release` messes my pattern up somehow. Are brace expansions unsupported at all? I had a quick look to the code and could not identify any such thing.
