### ISSUE TITLE
Getting: HttpError: token ***  is not a legal HTTP header value

### ISSUE THREAD

**Issue by wustho** [softprops/action-gh-release#209]
Here is my workflow:
```
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install windows-curses pyinstaller
      - name: Build binary
        run: |
          pyinstaller --onefile --name epy-win epy.py
      - name: Release Windows Binary
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/epy-win.exe
          token: ${{ secrets.GH_TOKEN }}
```

But I always got this error:
```
Run softprops/action-gh-release@v1
  with:
    files: ./dist/epy-win.exe
    token: ***
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.10.1\x64
    GITHUB_TOKEN: ***
  
⚠️ Unexpected error fetching GitHub release for tag refs/tags/v2022.2.14: HttpError: token ***
 is not a legal HTTP header value
Error: token ***
 is not a legal HTTP header value
```

Do you think maybe the header should be `authorization: Bearer ${{ secrets.GITHUB_TOKEN }}` with `Bearer` instead of `token`? I'm not sure myself, haven't read much into github api docs...
