### ISSUE TITLE
Creating a release from a tag fails with error 422

### ISSUE THREAD

**Issue by lukasz-kalnik-gcx** [softprops/action-gh-release#213]
I try to create a GitHub release with a workflow started manually.
In the "Run workflow" pull down menu, for "Use workflow from" I select a tag `bgo/sprint/s09`:

<img width="324" alt="image" src="https://user-images.githubusercontent.com/70261110/155000870-8134984b-edb9-4fce-95bf-11a1f9278e49.png">

Then I fill out the rest of the fields for our custom inputs. The created release tag is set in the "Tag name" field as `bgo/release/v1.8.0`:

<img width="324" alt="image" src="https://user-images.githubusercontent.com/70261110/155001287-ec37529e-d697-4ced-93c4-2578a912d182.png">

The code is checked out from tag `bgo/sprint/s09` correctly and builds without problems.

However when creating a GitHub release I get a 422 error. The action then retries in a loop but everytime gets the same response:

```
Creating new GitHub release for tag bgo/release/v1.8.0 using commit "refs/tags/bgo/sprint/s09"...
⚠️ GitHub release failed with status: 422
[{"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not a valid tag"},{"resource":"Release","code":"custom","message":"Published releases must have a valid tag"},{"resource":"Release","code":"invalid","field":"target_commitish"}]
```

This doesn't happen when in the initial configuration of "Use workflow from" I select a branch (like `main`).

The workflow .yml file looks like this:
```
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v0.1.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ github.ref }}
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_name }}
          body: ${{ github.event.inputs.release_notes }}
          draft: false
          prerelease: false
          files: |
            myapp/app/build/outputs/apk/play/release/**.apk
            myapp/app/build/outputs/mapping/playRelease/**
            myapp/app/build/outputs/bundle/playRelease/**.aab
```
