### ISSUE TITLE
Error on release: [{"resource":"Release","code":"invalid","field":"target_commitish"}]

### ISSUE THREAD

**Issue by DarkWanderer** [softprops/action-gh-release#214]
Hi, 

I'm a new user of this action - and it does not seem to work for me, with error in title
`[{"resource":"Release","code":"invalid","field":"target_commitish"}]`
Parameters:
```
Run softprops/action-gh-release@v1
  with:
    draft: true
    prerelease: false
    generate_release_notes: true
    target_commitish: refs/tags/4.[2](https://github.com/DarkWanderer/ClickHouse.Client/runs/5307034037?check_suite_focus=true#step:3:2).2
    tag_name: [4](https://github.com/DarkWanderer/ClickHouse.Client/runs/5307034037?check_suite_focus=true#step:3:4).2.2
    name: 4.2.2
    files: ClickHouse.Client.*.nupkg
  ClickHouse.Client.*.snupkg
```
Example run: [here](https://github.com/DarkWanderer/ClickHouse.Client/runs/5307034037?check_suite_focus=true)

**Comment by lukasz-kalnik-gcx** [comment]
This is because in Git a tag is not the same as commit or a branch.
You need to take the `sha` of the tag as `target_commitish`:
https://github.com/softprops/action-gh-release/issues/213

**Comment by lukasz-kalnik-gcx** [comment]
See also the action documentation here: https://github.com/softprops/action-gh-release#inputs
It says that `target_commitish` needs to be a SHA. In your script `target_commitish` is just a reference to a tag with some URL (which looks wrong actually, is this really what you have in your script?):
```
target_commitish: refs/tags/4.[2](https://github.com/DarkWanderer/ClickHouse.Client/runs/5307034037?check_suite_focus=true#step:3:2).2
```

**Comment by DarkWanderer** [comment]
>  (which looks wrong actually, is this really what you have in your script?):

No, this a copy-paste issue, the actual parameters are
```
with:
    draft: true
    prerelease: false
    generate_release_notes: true
    target_commitish: refs/tags/4.2.2
    tag_name: 4.2.2
    name: 4.2.2
    files: ClickHouse.Client.*.nupkg
  ClickHouse.Client.*.snupkg
```

What is the correct set of parameters I should use if I want to drive the release from existing tag rather than let action create that tag?

**Comment by lukasz-kalnik-gcx** [comment]
First of all, you should not hardcode your input parameters into the action scripts.

We take the `target_commitish` from the GitHub Action input dropdown where you select a branch or a tag:

<img width="338" alt="image" src="https://user-images.githubusercontent.com/70261110/157883440-a6675cb3-6a16-4dfc-b55e-32ce1520b298.png">

And then you can reference the branch or a tag  using GitHub context variable:

```
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          target_commitish: ${{ github.sha }}
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_name }}
          body: ${{ github.event.inputs.release_notes }}
```

The rest of the parameters we also input when triggering the action manually:

```
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'PlayStore Release name, e.g. Play Release Version 1.2.0'
        required: true
        default: 'Play Release Version X.X.X'
      tag_name:
        description: 'Tag name, format: release/vX.X.X, e.g. release/v1.2.3'
        required: true
        default: 'release/vX.X.X'
      release_notes:
        description: 'Release notes'
        required: false
        default: 'Not provided'
```

**Comment by DarkWanderer** [comment]
Firstly, I do not hardcode the parameters into script - not sure where you took that from. I've pasted the parameters as displayed by the action log

Secondly, `commitish` in Git terms [means anything that points to commit](https://stackoverflow.com/questions/23303549/what-are-commit-ish-and-tree-ish-in-git) - e.g. commit hash, tag, branch name, `HEAD` etc., so `target_commitish` looks like a misnomer. The doc also says "Can be any branch or commit SHA. Defaults to repository default branch." - looks like the documentation is wrong in that case

Thirdly, my use case is not to launch a workflow manually, but rather run it automatically on new tag push. Is it possible, or will the action always try to create a tag?

**Comment by lukasz-kalnik-gcx** [comment]
> Firstly, I do not hardcode the parameters into script - not sure where you took that from. I've pasted the parameters as displayed by the action log

Sorry, it was not clear to me - your log looks exactly like contents of a `.yml` workflow config file.

> Secondly, `commitish` in Git terms [means anything that points to commit](https://stackoverflow.com/questions/23303549/what-are-commit-ish-and-tree-ish-in-git) - e.g. commit hash, tag, branch name, `HEAD` etc., so `target_commitish` looks like a misnomer. The doc also says "Can be any branch or commit SHA. Defaults to repository default branch." - looks like the documentation is wrong in that case

Yes, I agree the `target_commitish` name is misleading - I had exactly the same problem that until I read the documentation I didn't know that it should actually resolve to a SHA.
But I guess it doesn't make sense to change the name now, because of backwards compatibility.
BTW it's not the documentation that is wrong - it's actually the `target_commitish` name that is misleading.

> Thirdly, my use case is not to launch a workflow manually, but rather run it automatically on new tag push. Is it possible, or will the action always try to create a tag?

I think you are conflating two things here:
1. Passing a tag as `target_commitish` doesn't trigger creating a new tag. The action creates a new tag because your script provided:
```
tag_name: 4.2.2
```

2. The reason why the action fails is because your script passes a tag name (instead of a SHA) as `target_commitish`:
```
target_commitish: refs/tags/4.2.2
```

I already provided you a solution in my previous answer: you should set in your script the following configuration for the action:

```
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          target_commitish: ${{ github.sha }}
```
`github.sha` is a context variable which will provide the `SHA` of the tag/branch/commit with which the build was started.

If it still doesn't work please provide a snippet of your workflow `.yml` file.
