### ISSUE TITLE
GitHub release failed with status: 404 undefined

### ISSUE THREAD

**Issue by skirpichev** [softprops/action-gh-release#217]
See [the build log](https://github.com/diofant/diofant/runs/5402391352?check_suite_focus=true).  No workflow changes since last release [v0.13.0](https://github.com/diofant/diofant/releases/tag/v0.13.0):
```
    - name: Publish on Github Releases
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && matrix.coverage
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASES_DEPLOY_KEY }}
      with:
        files: |
          dist/*
          build/sphinx/latex/Diofant-*.pdf
        draft: true
        prerelease: true
        name: "Diofant ${{ steps.release.outputs.version }}"
        body: "See [release notes](https://diofant.readthedocs.io/\
               en/latest/release/notes-${{ steps.release.outputs.short_version }}.html)."
```
