### ISSUE TITLE
The field body_path is not working

### ISSUE THREAD

**Issue by psanders** [softprops/action-gh-release#22]
I've trying to use the `body_path` but it does not shows in the release body. My configuration is as follows

```yml
name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: Release.txt
          prerelease: false
          files: |
            Release.txt
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I try using different paths but with any success. I'm doing anything wrong? 

Thanks in advance
