### ISSUE TITLE
Issue with outputs.assets

### ISSUE THREAD

**Issue by toroConverter** [softprops/action-gh-release#222]
Hi everyone, I'm running this simple workflow to understand well how this action works:

```
name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: echo ${{ github.sha }} > Release.txt

      - name: Test
        run: cat Release.txt

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: Release.txt
          tag_name: ${{ github.ref_name }}

      - run: |
          echo ${{ steps.release.outputs.url }}
          echo ${{ steps.release.outputs.id }}
          echo ${{ steps.release.outputs.upload_url }}
          echo ${{ steps.release.outputs.assets }}
```

windows-2019 is a constraint of my future application,

This workflow creates the new release and print all the outputs except `steps.release.outputs.assets`. 
Any idea on why?
