### ISSUE TITLE
[Question] How to trigger another workflow by the release

### ISSUE THREAD

**Issue by serkonda7** [softprops/action-gh-release#224]
I have a second workflow and try to use these on rules to run on a release https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
However doesn't it trigger. What event should be used or is there another way?

**Comment by ainvoner** [comment]
I hope I understand the issue you are facing...
If your first workflow creates the release (meaning the release exists after the workflow is done). you can do the following in your second workflow:
```
on:
  workflow_run:
    workflows: [Release]
    types:
      - completed
```
