### ISSUE TITLE
How to determine whether to upload an asset through a condition

### ISSUE THREAD

**Issue by YangJiao0817** [softprops/action-gh-release#229]
Hi everyone,
Suppose I have two assets, one is A asset and the other is B asset,
When RC release I want to upload A asset but not upload B asset, when GA I want to upload A asset and B asset, I want to know how to do this.
It would be nice if could specify the file directory where the asset is uploaded. 
Then upload all files in the specified directory.
For example,
```
name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files_directory: ${files_directory}

```
