### ISSUE TITLE
Unexpected error fetching GitHub release for tag refs/tags/v1.0.1: HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by aminya** [softprops/action-gh-release#232]
I am trying to use this action to push binaries on the tags, but I get this error:
```
⚠️ Unexpected error fetching GitHub release for tag refs/tags/v1.0.1: HttpError: Resource not accessible by integration
Error: Resource not accessible by integration
```
https://github.com/aminya/cmove/runs/6463813402?check_suite_focus=true#step:10:48

Here is my yaml file:
```yaml
      - name: Publish Tagged Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.CPACK_GENERATOR != '' && matrix.os == 'ubuntu-20.04' && matrix.compiler == 'llvm' }}
        with:
          files: |
            build/cmove-*.zip
```
