### ISSUE TITLE
Fail with undefined 403 on windows-latest

### ISSUE THREAD

**Issue by liubai01** [softprops/action-gh-release#235]
On my windows-latest action of private repository, it shows:
```
Run softprops/action-gh-release@v1
👩‍🏭 Creating new GitHub release for tag CDTest0.0.3...
⚠️ GitHub release failed with status: 403
undefined
retrying... (2 retries remaining)
👩‍🏭 Creating new GitHub release for tag CDTest0.0.3...
⚠️ GitHub release failed with status: 403
undefined
retrying... (1 retries remaining)
👩‍🏭 Creating new GitHub release for tag CDTest0.0.3...
⚠️ GitHub release failed with status: 403
undefined
retrying... (0 retries remaining)
❌ Too many retries. Aborting...
Error: Too many retries.
```

My config is:
```
name: MSBuild

on:
  push:
    tags:
      - '*'

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Debug

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
    - name: Package
      run: 7z a win10_debug_x64.zip x64
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ github.event.head_commit.message }}
        files: |
          win10_debug_x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Refer to previous issues: https://github.com/softprops/action-gh-release/issues/94#issue-854973442, which is led by the wrong permission setup, I have checked that it is configured correctly.
