### ISSUE TITLE
append_body are not expected as inputs

### ISSUE THREAD

**Issue by tuxtof** [softprops/action-gh-release#238]
I have the following actions

```
    - name: create release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: true
        body_path: ${{ github.workspace }}-CHANGELOG.txt
        generate_release_notes: true
        append_body: true
        files: |
          xxx.yaml
          yyy.yaml
          zzz.yaml
```
every time I launch it I have the following warning

[Build Release]
Unexpected input(s) 'append_body', valid inputs are ['body', 'body_path', 'name', 'tag_name', 'draft', 'prerelease', 'files', 'fail_on_unmatched_files', 'repository', 'token', 'target_commitish', 'discussion_category_name', 'generate_release_notes']

???
