### ISSUE TITLE
Please tell me how to cooperate with release-drafter@v5 I have a problem.

### ISSUE THREAD

**Issue by duolabmeng6** [softprops/action-gh-release#246]
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/59047063/181012566-7118821a-f71c-45c1-a5fa-15027d19d7ab.png">

May I ask how to publish only one draft?

```
name: 版本信息发布

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [opened, reopened, synchronize]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write 
    runs-on: ubuntu-latest
    steps:
      # 写出版本号以及变化记录
      - uses: release-drafter/release-drafter@v5
        id: create_release
        # 配置文件在 .github/release-drafter.yml
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 构建软件
        run: |
          mkdir down
          echo "123456789" >> ./down/QtEasyDesigner.exe
          echo "123456789" >> ./down/QtEasyDesigner_MacOS.zip
          ls -al

      - name: 发布资产文件
        uses: softprops/action-gh-release@v1
        with:
          draft: true # 草稿别人看不见 需要手动发布
          tag_name: ${{ steps.create_release.outputs.name }} # v0.1.1
          files: ./down/*

```
