### ISSUE TITLE
feature request: pass array to `files`

### ISSUE THREAD

**Issue by RodrigoDornelles** [softprops/action-gh-release#247]
it would be interesting to send more than one patern in the same step, I end up having to duplicate it because I need to send .zip and .tar.gz

### currently

```YAML
      - name: Upload binaries and libaries to github (tarballs)
        uses: softprops/action-gh-release@v1
        with:
          files: "*.tar.gz"

      - name: Upload binaries and libaries to github (zippies)
        uses: softprops/action-gh-release@v1
        with:
          files: "*.zip"
```

### suggestion

```YAML
      - name: Upload binaries and libaries to github
        uses: softprops/action-gh-release@v1
        with:
          files:
            - "*.tar.gz"
            - "*.zip"
```

**Comment by puzzle9** [comment]
try
```
- name: Upload binaries and libaries to github
uses: softprops/action-gh-release@v1
with:
  files: |
    "*.tar.gz"
    "*.zip"
```

https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets

**Comment by RodrigoDornelles** [comment]
> try
> 
> ```
> - name: Upload binaries and libaries to github
> uses: softprops/action-gh-release@v1
> with:
>   files: |
>     "*.tar.gz"
>     "*.zip"
> ```
> 
> https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets

dont work for me

![Screen Shot 2022-08-01 at 16 10 31](https://user-images.githubusercontent.com/29123479/182227483-d11e2e1b-6b40-4630-b644-2970bad92a7d.png)

**Comment by danielchalmers** [comment]
> > try
> > ```
> > - name: Upload binaries and libaries to github
> > uses: softprops/action-gh-release@v1
> > with:
> >   files: |
> >     "*.tar.gz"
> >     "*.zip"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets
> 
> dont work for me
> 
> ![Screen Shot 2022-08-01 at 16 10 31](https://user-images.githubusercontent.com/29123479/182227483-d11e2e1b-6b40-4630-b644-2970bad92a7d.png)

+1. I get the same error

**Comment by softprops** [comment]
Github actions only supports strings at this time so I need to work within those design constraints. The multi line syntax in the readme is yaml syntax for a multi line at string

I’m the suggestion above you are double quoting that string but placing quotes inside that string. Try removing those

```yaml
- name: Upload binaries and libaries to github
uses: softprops/action-gh-release@v1
with:
  files: |
    *.tar.gz
    *.zig
```

**Comment by RodrigoDornelles** [comment]
> Github actions only supports strings at this time so I need to work within those design constraints. The multi line syntax in the readme is yaml syntax for a multi line at string
> 
> I’m the suggestion above you are double quoting that string but placing quotes inside that string. Try removing those
> 
> ```yaml
> - name: Upload binaries and libaries to github
>   uses: softprops/action-gh-release@v1
>   with:
>     files: |
>       *.tar.gz
>       *.zip
> ```

doing this is not a valid yaml, and I had tested it before also in this case.

**Comment by gaetschwartz** [comment]
Has there been progress on this one ? I'm also looking for a way to specify multiple patterns

**Comment by wbadart** [comment]
I'm wondering if an error I've been getting is related. I see `Pattern '...' does not match any files` even when the pattern doesn't have a wildcard and is an exact match with the one file in the working directory:

<img width="652" alt="Screenshot 2023-03-03 at 19 56 37" src="https://user-images.githubusercontent.com/8717474/222874631-6e04557d-bae9-4b31-b27a-84cdd71dd779.png">

workflow:

```yaml
name: build
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # this step actually compiles a Nim program but I believe that's
    # beside the point for our purposes:
    - run: touch prices-ubuntu-latest
    - uses: actions/upload-artifact@v3
      with:
        name: prices-ubuntu-latest
        path: prices-ubuntu-latest

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
    - run: ls -al
    - uses: softprops/action-gh-release@v1
      with:
        files: |
          prices-ubuntu-latest
```
