### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by marwin1991** [softprops/action-gh-release#248]
Hello, I have a problem with this action and I cannot figure it out.

Action def:
```yaml

name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test files
        run: ls -l && ls -l ./changelog && echo "v${GITHUB_REF/refs\/tags\//}" && ls -l ./changelog/v${GITHUB_REF/refs\/tags\//}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          #  when tag has 'v' in name no need of adding it before ${GITHUB_REF/refs\/tags\//
          body_path: ./changelog/v${GITHUB_REF/refs\/tags\//}/version-summary.md
        env:
          # Cannot use GITHUB_TOKEN because of:
          # https://github.com/orgs/community/discussions/27028
          GITHUB_TOKEN: ${{ secrets.LOGCHANGE_PAT_TOKEN }}

```

And the logs
![image](https://user-images.githubusercontent.com/25181517/181425951-60a35d33-a96c-4e8b-9e2f-029cd76bbeb6.png)

**Comment by marwin1991** [comment]
No progress :(

![image](https://user-images.githubusercontent.com/25181517/181824681-ec1fe198-b014-49e6-80be-06bbf2178d48.png)

**Comment by marwin1991** [comment]
I cannot spot a problem :(

**Comment by marwin1991** [comment]
I solve it with:

```yml
      - name: Set env
        run: echo "RELEASE_BODY_FILE=$(echo $GITHUB_WORKSPACE/changelog/v${GITHUB_REF/refs\/tags\//}/version-summary.md)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          #  when tag has 'v' in name no need of adding it before ${GITHUB_REF/refs\/tags\//
          body_path: ${{ env.RELEASE_BODY_FILE }}
 ```
