### ISSUE TITLE
How to upload asses after completion of both Windows and Linux run

### ISSUE THREAD

**Issue by wxguy** [softprops/action-gh-release#256]
Here is my current setup I use for action:

```
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
```

In my case, windows run takes much more time to complete and build the executable than Linux VM. In such cases, how do I wait for Windows VM to complete the job and trigger the upload process to github release?

**Comment by konsumer** [comment]
I also have a similar question. I am not using `matrix` but I have windows, mac, linux (x86_64, arm7, and arm64) builds and I want to attach them all to a single release. I tried this:

```yml
jobs:
  publish:
    runs-on: ubuntu-latest
    needs: [windows, mac, linux]
    steps:
      - name: zip windows
        run: |
          cd build-windows-x86_64
          zip ../my_raylib_game-windows.zip my_raylib_game.exe
      - name: zip mac
        run: |
          cd build-mac-universal
          zip ../my_raylib_game-mac.zip my_raylib_game
      - name: zip linux-x86_64
        run: |
          cd build-linux-x86_64
          zip ../my_raylib_game-linux-x86_64.zip my_raylib_game
      - name: zip linux-arm64
        run: |
          cd build-linux-arm64
          zip ../my_raylib_game-linux-arm64.zip my_raylib_game
      - name: zip linux-arm7
        run: |
          cd build-linux-arm7
          zip ../my_raylib_game-linux-arm7.zip my_raylib_game
      - name: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            my_raylib_game-windows.zip
            my_raylib_game-mac.zip
            my_raylib_game-linux-x86_64.zip
            my_raylib_game-linux-arm64.zip
            my_raylib_game-linux-arm7.zip
  
  windows:
    # some build steps, first step is actions/checkout@v2
  mac:
    # some build steps, first step is actions/checkout@v2
  linux:
    # some build steps, first step is actions/checkout@v2
```

First it runs all the builds, but then the zip steps don't work. I tried sharing the `actions/checkout@v2` between all steps with a `needs` in each build-step, but then the builds don't work because it doesn't seem to share the filesystem.

Am I thinking about this wrong?
