### ISSUE TITLE
GITHUB_REPOSITORY env variable Not Work

### ISSUE THREAD

**Issue by ykla** [softprops/action-gh-release#258]
For example:

```
name: Main

on: push

jobs:
  build:
    name: Build and Deploy Webpages
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: get deb packgage for test
        run: git clone https://github.com/ykla/ttf-mswin11-zh-deb
        
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::test_$(date +"%Y.%m.%d_%H-%M")"
      - name: Release 
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: "ttf-mswin11-zh-deb/ttf-ms-win11-*.deb"
          body: ${{ github.sha }}
        env:
          GITHUB_REPOSITORY: FreeBSD-Ask/Handbook
```

It will not releases file to `FreeBSD-Ask/Handbook` and will releases in local repository. But

```
name: Main

on: push

jobs:
  build:
    name: Build and Deploy Webpages
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: get deb packgage for test
        run: git clone https://github.com/ykla/ttf-mswin11-zh-deb
        
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::test_$(date +"%Y.%m.%d_%H-%M")"
      - name: Release 
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: "ttf-mswin11-zh-deb/ttf-ms-win11-*.deb"
          body: ${{ github.sha }}
          repository: FreeBSD-Ask/Handbook
        env:
          GITHUB_REPOSITORY: FreeBSD-Ask/Handbook
```
will works well, and releases file to FreeBSD-Ask/Handbook, you must use `repository: FreeBSD-Ask/Handbook` not `GITHUB_REPOSITORY: FreeBSD-Ask/Handbook`.

But as README said :

<html>
<body>

repository | String | Name of a target repository in <owner>/<repo> format. Defaults to GITHUB_REPOSITORY env variable
-- | -- | --

</body>
</html>
