### ISSUE TITLE
Bad credentials (ubuntu-latest)

### ISSUE THREAD

**Issue by skirpichev** [softprops/action-gh-release#27]
See [example](https://github.com/diofant/diofant/commit/6d148c980620e3a38deaf628c77ddf22ee48f303/checks?check_suite_id=262214186).  This github action doesn't work at all...

Seems to be like (closed) https://github.com/softprops/action-gh-release/issues/12.

BTW, full yml snippet, that uses your software in my case:
```yml
    - name: Publish on Github Releases
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/*
        draft: true
        prerelease: true
        name: "Diofant ${VERSION}"
        body: "See [release notes](https://diofant.readthedocs.io/\
               en/latest/release/notes-${SHORT_VERSION}.html)."
```
