### ISSUE TITLE
default tag name not work

### ISSUE THREAD

**Issue by playgithub** [softprops/action-gh-release#270]
The github workflow below works well.
```yml
name: CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: suisei-cn/actions-download-file@v1.0.1
        id: downloadfile  # Remember to give an ID if you need the output filename
        with:
            url: "https://github.com/madler/zlib/releases/download/v1.2.13/zlib-1.2.13.tar.gz"
            target: downloads/
      - name: result
        run: echo downloads/${{ steps.downloadfile.outputs.filename }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            downloads/${{ steps.downloadfile.outputs.filename }}
          tag_name: 123
```

If remove `tag_name`, it fails with error: "Error: ⚠️ GitHub Releases requires a tag", but the doc for `tag_name` allows default:
<html>
<body>

tag_name | String | Name of a tag. defaults to github.ref
-- | -- | --

</body>
</html>

**Comment by andreasabel** [comment]
> If remove `tag_name`, it fails with error: "Error: ⚠️ GitHub Releases requires a tag", but the doc for `tag_name` allows default:

Yeah, but only if the github.ref is a valid tag.  You can ensure this by limiting your "Release" step e.g. to:
```
if: startsWith(github.ref, 'refs/tags/')
```

**Comment by TomasHubelbauer** [comment]
@andreasabel What can I do to make sure there is a release for every push to `main`? Do I need to use a different Action to create the tag first?

**Comment by fwextensions** [comment]
Thanks to @TomasHubelbauer's helpful edit, I was able to get this working, though I did need to add these to the script so that the `git push` would work:

```
git config user.name "GitHub Action"
git config user.email "bloop@blorp.com"
```

**Comment by geryit** [comment]
You create tags with another action: 

```yml
      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: false

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: linkedin-cv-scorer.zip
          tag_name: ${{ steps.bump.outputs.new_tag }}
```
