### ISSUE TITLE
Relasing to remote repository does not create new assets

### ISSUE THREAD

**Issue by SharkFourSix** [softprops/action-gh-release#308]
```yaml
- name: Publish to remote repository
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repository: RemoteOwner/RemoteRepo
          token: ${{ secrets.PUBLIC_RELEASE_TOKEN }}
          files: flie-to-release.zip
```

When it finds a similar file, it doesn't replace the file but simply creates a release with previous files. How to fix this please.

I would like to have a new *file-to-release.zip*, not the old ones.
