### ISSUE TITLE
[bug] failed to upload/skip files that are 0 byte

### ISSUE THREAD

**Issue by Loyalsoldier** [softprops/action-gh-release#321]
[Task link](https://github.com/Loyalsoldier/v2ray-rules-dat/actions/runs/4122883129/jobs/7120210407)

```shell
Error: Validation Failed: {"resource":"ReleaseAsset","code":"custom","field":"size","message":"size must be greater than or equal to 1"}
```

**Comment by topherbuckley** [comment]
I'm think I'm seeing this again:

```
⬆️ Uploading AudioTimestamp.java...
⬆️ Uploading BatteryData.java...
⬆️ Uploading ChargerData.java...
⬆️ Uploading CommAction.java...
⬆️ Uploading Episode.java...
⬆️ Uploading Image.java...
⬆️ Uploading ImageData.java...
⬆️ Uploading IndividualWheelData.java...
⬆️ Uploading MotionAction.java...
⬆️ Uploading OrientationData.java...
⬆️ Uploading RobotAction.java...
⬆️ Uploading SoundData.java...
⬆️ Uploading TimeStep.java...
⬆️ Uploading WheelData.java...
⬆️ Uploading __init__.py...
⬆️ Uploading __init__.py...
⬆️ Uploading __init__.py...
⬆️ Uploading __init__.py...
⬆️ Uploading __init__.py...
⬆️ Uploading __init__.py...
⬆️ Uploading AudioTimestamp.py...
⬆️ Uploading BatteryData.py...
⬆️ Uploading ChargerData.py...
⬆️ Uploading CommAction.py...
⬆️ Uploading Episode.py...
⬆️ Uploading Image.py...
⬆️ Uploading ImageData.py...
⬆️ Uploading IndividualWheelData.py...
⬆️ Uploading MotionAction.py...
⬆️ Uploading OrientationData.py...
⬆️ Uploading RobotAction.py...
⬆️ Uploading SoundData.py...
⬆️ Uploading TimeStep.py...
⬆️ Uploading WheelData.py...
Error: Validation Failed: {"resource":"ReleaseAsset","code":"custom","field":"size","message":"size must be greater than or equal to 1"}
```

Here is the workflow used:

```
name: Automated Build Release Publish

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: 'true'
    - name: Build
      with:
        gradle-encryption-key: ${{ secrets.GradleEncryptionKey }}
      uses: ./.github/actions/build
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ github.workspace }}/src/**/*
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref_name }}
        generate_release_notes: true
    - name: Publish package
      run: ./gradlew publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
Not sure its relevant, but here is the contents of the composite action as well:

```
name: 'Build'
description: 'openjdk17 install, setup-gradle, and gradle build into one'
permissions:
  contents: write
  packages: write
inputs:
  gradle-encryption-key:
    description: 'The encryption key to use for caching'
    required: true
runs:
  using: "composite"
  steps:
  - name: Install flatbuffers
    run: |
      sudo apt-get install -y flatbuffers-compiler
      flatc --version
    shell: bash
  - name: set up JDK
    uses: actions/setup-java@v4.2.1
    with:
      java-version: '17.0'
      distribution: 'temurin'
      cache: gradle
  - name: Setup Gradle
    uses: gradle/actions/setup-gradle@v3.3.2
    with:
      gradle-version: 8.6
      cache-encryption-key: ${{ inputs.gradle-encryption-key }}
      cache-read-only: false
      cache-overwrite-existing: true
  - name: Make directories
    run: |
      mkdir -p src/main/java
      mkdir -p src/main/python
    shell: bash
  - name: Build with flatc
    run: ./generate-classes.sh
    shell: bash
```

and finally the contents of generate-classes.sh
```
#!/bin/bash

flatc -b -j -o src/main/java/ episode.fbs
flatc -b -p -o src/main/python/ --force-empty-vectors episode.fbs
```

which is just generating a bunch of .java files and .py files in a bunch of subdirectories. Here is the output of `tree -L 10 src/` after running the script locally:

```
src/
└── main
    ├── java
    │   └── jp
    │       └── oist
    │           └── abcvlib
    │               └── core
    │                   └── learning
    │                       └── fbclasses
    │                           ├── AudioTimestamp.java
    │                           ├── BatteryData.java
    │                           ├── ChargerData.java
    │                           ├── CommAction.java
    │                           ├── Episode.java
    │                           ├── ImageData.java
    │                           ├── Image.java
    │                           ├── IndividualWheelData.java
    │                           ├── MotionAction.java
    │                           ├── OrientationData.java
    │                           ├── RobotAction.java
    │                           ├── SoundData.java
    │                           ├── TimeStep.java
    │                           └── WheelData.java
    └── python
        └── jp
            ├── __init__.py
            └── oist
                ├── abcvlib
                │   ├── core
                │   │   ├── __init__.py
                │   │   └── learning
                │   │       ├── fbclasses
                │   │       │   ├── AudioTimestamp.py
                │   │       │   ├── BatteryData.py
                │   │       │   ├── ChargerData.py
                │   │       │   ├── CommAction.py
                │   │       │   ├── Episode.py
                │   │       │   ├── ImageData.py
                │   │       │   ├── Image.py
                │   │       │   ├── IndividualWheelData.py
                │   │       │   ├── __init__.py
                │   │       │   ├── MotionAction.py
                │   │       │   ├── OrientationData.py
                │   │       │   ├── RobotAction.py
                │   │       │   ├── SoundData.py
                │   │       │   ├── TimeStep.py
                │   │       │   └── WheelData.py
                │   │       └── __init__.py
                │   └── __init__.py
                └── __init__.py
```

**Comment by topherbuckley** [comment]
I tried another globbing method thinking it was globbing onto directories `.` and `..`:
```
        files: |
          ${{ github.workspace }}/src/**/*.py
          ${{ github.workspace }}/src/**/*.java
```

but this still fails in the same way. 

I note that the 0 byte files are actually the __init__.py files, which are necessary for the python package to work correctly.:

```
find ./src -type f -exec du -h {} +
0	./src/main/python/jp/__init__.py
4.0K	./src/main/python/jp/oist/abcvlib/core/learning/fbclasses/WheelData.py
4.0K	./src/main/python/jp/oist/abcvlib/core/learning/fbclasses/Episode.py
4.0K	./src/main/python/jp/oist/abcvlib/core/learning/fbclasses/RobotAction.py
12K	./src/main/python/jp/oist/abcvlib/core/learning/fbclasses/IndividualWheelData.py
4.0K	./src/main/python/jp/oist/abcvlib/core/learning/fbclasses/ImageData.py
8.0K	./src/main/python/jp/oist/abcvlib/core/learning/fbclasses/OrientationData.py
8.0K	./src/main/python/jp/oist/abcvlib/core/learning/fbclasses/SoundData.py
4.0K	./src/main/python/jp/oist/abcvlib/core/learning/fbclasses/AudioTimestamp.py
8.0K	./src/main/python/jp/oist/abcvlib/core/learning/fbclasses/MotionAction.py
4.0K	./src/main/python/jp/oist/abcvlib/core/learning/fbclasses/BatteryData.py
4.0K	./src/main/python/jp/oist/abcvlib/core/learning/fbclasses/CommAction.py
8.0K	./src/main/python/jp/oist/abcvlib/core/learning/fbclasses/TimeStep.py
0	./src/main/python/jp/oist/abcvlib/core/learning/fbclasses/__init__.py
4.0K	./src/main/python/jp/oist/abcvlib/core/learning/fbclasses/ChargerData.py
4.0K	./src/main/python/jp/oist/abcvlib/core/learning/fbclasses/Image.py
0	./src/main/python/jp/oist/abcvlib/core/learning/__init__.py
0	./src/main/python/jp/oist/abcvlib/core/__init__.py
0	./src/main/python/jp/oist/abcvlib/__init__.py
0	./src/main/python/jp/oist/__init__.py
4.0K	./src/main/java/jp/oist/abcvlib/core/learning/fbclasses/MotionAction.java
4.0K	./src/main/java/jp/oist/abcvlib/core/learning/fbclasses/Episode.java
12K	./src/main/java/jp/oist/abcvlib/core/learning/fbclasses/IndividualWheelData.java
4.0K	./src/main/java/jp/oist/abcvlib/core/learning/fbclasses/AudioTimestamp.java
4.0K	./src/main/java/jp/oist/abcvlib/core/learning/fbclasses/RobotAction.java
4.0K	./src/main/java/jp/oist/abcvlib/core/learning/fbclasses/BatteryData.java
8.0K	./src/main/java/jp/oist/abcvlib/core/learning/fbclasses/SoundData.java
4.0K	./src/main/java/jp/oist/abcvlib/core/learning/fbclasses/ChargerData.java
8.0K	./src/main/java/jp/oist/abcvlib/core/learning/fbclasses/OrientationData.java
4.0K	./src/main/java/jp/oist/abcvlib/core/learning/fbclasses/Image.java
4.0K	./src/main/java/jp/oist/abcvlib/core/learning/fbclasses/ImageData.java
4.0K	./src/main/java/jp/oist/abcvlib/core/learning/fbclasses/CommAction.java
8.0K	./src/main/java/jp/oist/abcvlib/core/learning/fbclasses/TimeStep.java
4.0K	./src/main/java/jp/oist/abcvlib/core/learning/fbclasses/WheelData.java
```

**Comment by topherbuckley** [comment]
As a workaround, and probably better anyway, I just zip everything before releasing it:

```
name: Automated Build Release Publish

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: 'true'
    - name: Build
      with:
        gradle-encryption-key: ${{ secrets.GradleEncryptionKey }}
      uses: ./.github/actions/build
    - name: Zip release files into Java and Python packages
      run: |
        sudo apt-get install zip tar
        zip -r ./python.zip ./src/main/python
        zip -r ./java.zip ./src/main/java
        tar -czvf ./python.tar.gz ./src/main/python
        tar -czvf ./java.tar.gz ./src/main/java
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./python.zip
          ./python.tar.gz
          ./java.zip
          ./java.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref_name }}
        generate_release_notes: true
    - name: Publish package
      run: gradle publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
