### ISSUE TITLE
File pattern not matching file name

### ISSUE THREAD

**Issue by SecretX33** [softprops/action-gh-release#324]
## Introduction

Hi, I'm having issues regarding artifact upload when creating new releases. For some reason, `action-gh-release@v1` is not picking up my artifacts when I attempt to specify a name pattern for it, it only picks them up if I use `**` for the filename.

I would like to know why this is happening, and if it is a bug, expected behavior, or even if I'm messing up its configuration somehow.

The artifact is indeed being successfully built and is in the path `./dist/binary-file.zip`, confirmed by using `ls` on the `./` folder, as well as on the `dist` folder before running the `Create release` step.

## Current configuration

This is my current action configuration.

```yml
- name: Create release
  uses: softprops/action-gh-release@v1
  with:
    name: v${{ inputs.VERSION_TAG }}
    tag_name: ${{ inputs.VERSION_TAG }}
    draft: false
    prerelease: false
    fail_on_unmatched_files: false
    files: |
      ./dist/binary-file.zip
```

And this is the output for almost all patterns I've tried.

```
Run softprops/action-gh-release@v1
🤔 Pattern './dist/binary-file.zip' does not match any files.
👩‍🏭 Creating new GitHub release for tag snapshot...
🤔 ./dist/binary-file.zip not include valid file.
🎉 Release ready at https://github.com/SecretX33/test-rust-workflow/releases/tag/snapshot
```

## What I have tried

I have tried many, many different file patterns but none of them seemed to have worked, except for when I use `**` for the file name, these are some notable examples I've tested so far.

**Does not work**
```
# File path patterns
./**.zip
dist/*.zip
dist/**.zip
./dist/*
./dist/**.zip
./dist/binary-*.zip
./dist/binary-*.*

# Not even providing the full file path works
./dist/binary-file.zip
```

**Does work**
```
# These two are the only ones that worked so far
./**
./dist/**
```

## Reproducible test case

I've created a [reproducible repository](https://github.com/SecretX33/test-rust-workflow) that anyone can use to test this. The workflow name that I'm using to test this is the `Release Test`.

The original intention behind this repository was to test the entire workflow (which explains the repository name), so the files are from my other (open-source) project called [ZipSource](https://github.com/SecretX33/ZipSource), please don't mind the contents, the only important part is the Workflow.
