### ISSUE TITLE
Not upload file to release

### ISSUE THREAD

**Issue by stefanJi** [softprops/action-gh-release#33]
My config as follow:
```
name: Release
on:
  push:
    tags:
      - "release-v*"

jobs:
  release-to-gitHub:
    name: Release to github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Asseble release
        run: |
          ./gradlew app:assembleRelease --info
          cp app/build/outputs/apk/release/app-release.apk ${GITHUB_REF:10}.apk
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: ${GITHUB_REF:10}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Runtime log:
```
Run softprops/action-gh-release@v1
👩‍🏭 Creating new GitHub release for tag release-v1.0.2...
🎉 Release ready at https://github.com/stefanJi/dots365/releases/tag/release-v1.0.2
```

But release not file. See https://github.com/stefanJi/dots365/releases/tag/release-v1.0.2
