### ISSUE TITLE
Release notes fail to generate when used from a reusable workflow

### ISSUE THREAD

**Issue by herebebeasties** [softprops/action-gh-release#337]
GitHub has reusable workflow support:
https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow

However if you embed this action in a reusable workflow, the release notes step does not work:

```
👩‍🏭 Creating new GitHub release for tag v1.0.0...
🤔  not include valid file.
```

The reusable workflow has:
```
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ success() && startsWith(github.ref, 'refs/tags/v') }}
        with:
          generate_release_notes: true
```

**Comment by adam-grant-hendry** [comment]
The same issue occurs for tags. Reused workflows don't see generated tags (i.e. `git describe --tags` fails): [workflow run](https://github.com/adam-grant-hendry/poetry_plugin_constrain/actions/runs/6525775069/job/17718812598).

![image](https://github.com/softprops/action-gh-release/assets/59346180/8023e212-df5b-4df0-8330-75ece9dc95e2)

**Comment by adam-grant-hendry** [comment]
> The same issue occurs for tags. Reused workflows don't see generated tags

Actually, this looks like it was due to the `fetch-depth` of `actions/checkout`. Once I used:

```yaml
- name: Checkout
   uses: actions/checkout@v4
   with:
     fetch-depth: 0  # Entire history; See: https://github.com/actions/checkout/issues/206
     fetch-tags: true
```

it worked.

@herebebeasties Since your step checks for tags (`startsWith(github.ref, 'refs/tags/v')`), do you checkout tags? By default, `actions/checkout` uses a `fetch-depth=1` and doesn't check out tags.
