### ISSUE TITLE
Artefacts not being uploaded to release

### ISSUE THREAD

**Issue by eggbean** [softprops/action-gh-release#342]
I have made a GitHub Action to make [mosh ](https://github.com/mobile-shell/mosh)statically-linked binaries. I am updating another person's build action which used the deprecated release action.

I have a multi-architecture matrix which builds successfully, packages the files and uploads the zipped artefact:

```
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: mosh-${{ matrix.arch }}
          path: |
            files/mosh
            files/mosh-client
            files/mosh-server
            files/man/mosh.1
            files/man/mosh-client.1
            files/man/mosh-server.1
            files/bash-completion/mosh
          if-no-files-found: error
```
I see the uploaded artefacts called `mosh-x86_64` and `mosh-aarch64` in the web interface.

Then in the same actions.yml a new instance does the release like this:

```
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Get release version
        run: |
          export tag="$(curl -s https://api.github.com/repos/mobile-shell/mosh/releases/latest | jq -r '.tag_name')"
          echo "version=${tag}" >> $GITHUB_ENV

      - name: Publish archives and packages
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          files: |
            mosh-x86_64
            mosh-aarch64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

It makes the release but there are no files. How do I get those files and upload them as `.tar.gz` tarballs?

Also, how can I make those binaries executable before making the release? If I `chmod +x` the files before uploading the artefacts, the executable bit is lost.

What's the best way of doing what I have attempted here? Thanks.

**Comment by LucasJC** [comment]
Try to run an ls command to see how your files are being downloaded. 
I suspect your artifacts are inside an extra folder.

- run: ls -lhrt

**Comment by RalfJung** [comment]
I think I have a similar issue...
```
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./binaries

      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./binaries/*
```
The logs say artifacts are downloaded as
```
Artifact cargo-careful.exe was downloaded to /home/runner/work/cargo-careful/cargo-careful/binaries/cargo-careful.exe
Artifact cargo-careful-x86_64-apple-darwin was downloaded to /home/runner/work/cargo-careful/cargo-careful/binaries/cargo-careful-x86_64-apple-darwin
Artifact cargo-careful-x86_64-unknown-linux-musl was downloaded to /home/runner/work/cargo-careful/cargo-careful/binaries/cargo-careful-x86_64-unknown-linux-musl
Artifact download has finished successfully
```
but then the release action says
```
 🤔 Pattern './binaries/*' does not match any files.
👩‍🏭 Creating new GitHub release for tag v0.3.2...
🤔 ./binaries/* not include valid file.
```

**Comment by RalfJung** [comment]
I added some `ls` for debugging and it looks as expected. `ls -lah binaries` prints
```
drwxr-xr-x 5 runner docker 4.0K Apr 22 13:17 .
drwxr-xr-x 7 runner docker 4.0K Apr 22 13:17 ..
drwxr-xr-x 2 runner docker 4.0K Apr 22 13:17 cargo-careful-x86_64-apple-darwin
drwxr-xr-x 2 runner docker 4.0K Apr 22 13:17 cargo-careful-x86_64-unknown-linux-musl
drwxr-xr-x 2 runner docker 4.0K Apr 22 13:17 cargo-careful.exe
```
But for some reason the softprop action claims that `./binaries/*` does not match any file.

**Comment by Axteli** [comment]
> I have made a GitHub Action to make [mosh ](https://github.com/mobile-shell/mosh)statically-linked binaries. I am updating another person's build action which used the deprecated release action.
> 
> I have a multi-architecture matrix which builds successfully, packages the files and uploads the zipped artefact:
> 
> ```
>       - name: Upload package
>         uses: actions/upload-artifact@v3
>         with:
>           name: mosh-${{ matrix.arch }}.tar.gz
>           path: mosh-${{ matrix.arch }}.tar.gz
>         if-no-files-found: error
> ```
> 
> I see the uploaded artefacts called `mosh-x86_64.tar.gz` and `mosh-aarch64.tar.gz` in the web interface.
> 
> Then in the same actions.yml a new instance does the release like this:
> 
> ```
>   release:
>     needs: [build]
>     runs-on: ubuntu-latest
>     steps:
>       - name: Get release version
>         run: |
>           export tag="$(curl -s https://api.github.com/repos/mobile-shell/mosh/releases/latest | jq -r '.tag_name')"
>           echo "version=${tag}" >> $GITHUB_ENV
> 
>       - name: Download packages
>         uses: actions/download-artifact@v3
> 
>       - name: Publish archives and packages
>         uses: softprops/action-gh-release@v1
>         with:
>           tag_name: ${{ env.version }}
>           files: |
>             mosh-x86_64.tar.gz
>             mosh-aarch64.tar.gz
>         env:
>           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
> ```
> 
> The tarballs don't appear in the release and the log ends with this:
> 
> ```
> 2023-03-27T00:21:52.8210661Z 🤔 Pattern 'mosh-x86_64.tar.gz' does not match any files.
> 2023-03-27T00:21:52.8213299Z 🤔 Pattern 'mosh-aarch64.tar.gz' does not match any files.
> 2023-03-27T00:21:53.4174666Z 🤔 mosh-x86_64.tar.gz,mosh-aarch64.tar.gz not include valid file.
> ```
> 
> What am I doing wrong?

The problem is that when you upload an artifact like this :
```
        - uses: actions/upload-artifact@v3
          with:
            name: mosh.tar.gz
            path: mosh.tar.gz
```
and then download it with `actions/download-artifact`, the path to your tar.gz file will be `name_you_give/name_of_your_file`, so in your case `mosh.tar.gz/mosh.tar.gz`.

So you need to do this : 
```
      - name: Publish archives and packages
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          files: |
            mosh-x86_64.tar.gz/mosh-x86_64.tar.gz
            mosh-aarch64.tar.gz/mosh-aarch64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Hope this resolve your problem @eggbean and @RalfJung.

**Comment by RalfJung** [comment]
Oh I see, cargo-careful.exe is a directory in my ls... That is surely confusing (not your code of course). Thanks for the hint.

**Comment by Roms1383** [comment]
I think I also get the same issue:

the first are first uploaded :

```yml
- name: ↗️ upload artifact
   uses: actions/upload-artifact@v3
   with:
     name: mdbook-codeblocks-v${{ steps.tagName.outputs.version }}-${{ matrix.flavor.target }}.${{ matrix.flavor.ext }}
     path: mdbook-codeblocks-v${{ steps.tagName.outputs.version }}-${{ matrix.flavor.target }}.${{ matrix.flavor.ext }}
```

<img width="1152" alt="upload-artifact-job" src="https://user-images.githubusercontent.com/21016014/233877888-20dfda80-cd6a-4ec7-9985-194eee7c9a8f.png">

then in a subsequent job they get downloaded to `artifacts` folder :

```yml
- name: ↙️ download artifacts
  uses: actions/download-artifact@v3
  with:
    path: artifacts
```

<img width="1153" alt="download-artifact-job" src="https://user-images.githubusercontent.com/21016014/233877939-4b92cdf3-1ed6-408a-945a-70c2b362608d.png">

but weirdly, once creating the release it states that files pattern does not yield any result :

```yml
- name: 🔖 create GitHub release
  uses: softprops/action-gh-release@v1
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    name: v${{ steps.tagName.outputs.version }}
    files: |
      artifacts/mdbook-codeblocks-v${{ steps.tagName.outputs.version }}-aarch64-apple-darwin.tar.gz
      artifacts/mdbook-codeblocks-v${{ steps.tagName.outputs.version }}-x86_64-apple-darwin.tar.gz
      artifacts/mdbook-codeblocks-v${{ steps.tagName.outputs.version }}-x86_64-pc-windows-msvc.zip
      artifacts/mdbook-codeblocks-v${{ steps.tagName.outputs.version }}-x86_64-pc-windows-gnu.zip
      artifacts/mdbook-codeblocks-v${{ steps.tagName.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz
      artifacts/mdbook-codeblocks-v${{ steps.tagName.outputs.version }}-x86_64-unknown-linux-musl.tar.gz
```

<img width="1148" alt="create-github-release-path" src="https://user-images.githubusercontent.com/21016014/233878002-4eabf279-5ddb-4977-9e3c-aed6785fb9b1.png">
