### ISSUE TITLE
Release url in the body

### ISSUE THREAD

**Issue by MangaD** [softprops/action-gh-release#349]
Is there any way to have the release URL in the body? Something like:

```yaml
- name: Create Release
  id: create_release
  uses: softprops/action-gh-release@v0.1.15
  with:
    name: Release ${{ github.ref_name }}
    draft: false
    prerelease: false
    files: |
      artifact.zip
    body: |
      Download: [artifact.zip](${{ url }}/artifact.zip)
```

**Comment by kevinmatthes** [comment]
You could create the URL in another step and call it using the GitHub output semantics:

```yaml
      - id: release_url
        run: echo "url=example-url" >> "$GITHUB_OUTPUT"

      - uses: softprops/action-gh-release@v0.1.15
        with:
         body: |
           Download: [artifact.zip](${{ steps.release_url.outputs.url }}/artifact.zip) # example-url/artifact.zip
```
