### ISSUE TITLE
about shell $

### ISSUE THREAD

**Issue by 8MiYile** [softprops/action-gh-release#354]
how time to support 
```yaml
files: "$(find build/libs -type f|grep -v "sources")"
```
or
```yaml
      -
        id: getFiles
        run: |
          echo "name="$(find build/libs -type f|grep -v "sources"|grep -v "json")"" >> $GITHUB_OUTPUT
#--------------------
          files: "${{ steps.getFiles.outputs.name }}"
```
just i don't like update sources.jar
