### ISSUE TITLE
A release problem

### ISSUE THREAD

**Issue by Sinetian** [softprops/action-gh-release#364]
While using this action, I did not set a token in `step.with`, then `GitHub release failed with status: 403`.
[This repository](https://github.com/huanghongxun/HMCL/blob/javafx/.github/workflows/check-update.yml) did like me, but
I didn't found problems there.
My Actions file looks like this:
```yaml
name: Java check with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Get short SHA
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
    - name: Generate release note
      run: |
        echo "JTool Release ${{ env.SHORT_SHA }}" >> RELEASE_NOTE
        echo "" >> RELEASE_NOTE
        echo "JTool已于$(date +'%Y').$(date +'%m').$(date +'%d')更新。" >> RELEASE_NOTE 
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        body_path: RELEASE_NOTE
        files: target/dict-1.0.jar
        name: JTool release ${{ env.SHORT_SHA }} 
        tag_name: v$(date +'%Y').$(date +'%m').$(date +'%d')
```

**Comment by recke96** [comment]
You need to add 
```
permissions:
      contents: write
```
to the job. See [the README](https://github.com/softprops/action-gh-release#permissions).

**Comment by Sinetian** [comment]
Sorry, but now it said the tag name is invalid. Except the permissions, I changed nothing in my actions file.

**Comment by kevinmatthes** [comment]
@Sinetian

In addition to setting the permissions, you need to assemble the tag name in another step of the same job and call the tag name using the GitHub output semantics.  Here is an example:

```yaml
      - id: tag_name
        run: echo "version=$(date +v%Y.%m.%d)" >> "$GITHUB_OUTPUT"

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_name.outputs.version }}
          # Your other settings are left unchanged.
```

The invalid tag name error is caused due to a GitHub workflow syntax violation; it is not allowed to execute shell scripts as inputs for Actions.  If you would like to avoid such issues in the future, I recommend to apply a linter for GitHub Actions; I worked with https://github.com/devops-actions/actionlint, so far.
