### ISSUE TITLE
Home directory cannot be accessed via ~

### ISSUE THREAD

**Issue by LightTab2** [softprops/action-gh-release#368]
**Description:**
I think that the home directory cannot be accessed via `~`. It does not fail, but cannot find the files that obviously should be there.

**To Reproduce:**
1. Checkout repository with a file.
2. Move the file to `~`.
3. Try to upload it using this action.

Example Github Action:
```yaml
name: Ubuntu

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Move file
        run: mv ./README.md ~/README.md

      - name: Create release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: ~/README.md
          tag_name: issue
          token: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior:**
The file from home directory is uploaded to the release.

**Additional Info:**
* OS: Ubuntu 20.04
* Commit: [de2c0eb](https://github.com/softprops/action-gh-release/commit/de2c0eb89ae2a093876385947365aca7b0e5f844)
