### ISSUE TITLE
422 error 'body is too long'

### ISSUE THREAD

**Issue by joshuasimon-taulia** [softprops/action-gh-release#374]
when running this example workflow step against an older repo with a lot of commits:
```
    - name: Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      with:
        tag_name: ${{ inputs.git-tag }}
        body_path: ../changelog.md
        token: ${{ env.GITHUB_TOKEN_ORG }}
        generate_release_notes: ${{ inputs.changelog == '' && true || false }}
        repository: ${{ github.repository }}
```

it fails with
```
Run softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
👩‍🏭 Creating new GitHub release for tag v0.1.0...
⚠️ GitHub release failed with status: 422
[{"resource":"Release","code":"custom","field":"body","message":"body is too long (maximum is 125000 characters)"}]
retrying... (2 retries remaining)
👩‍🏭 Creating new GitHub release for tag v0.1.0...
⚠️ GitHub release failed with status: 422
[{"resource":"Release","code":"custom","field":"body","message":"body is too long (maximum is 125000 characters)"}]
retrying... (1 retries remaining)
👩‍🏭 Creating new GitHub release for tag v0.1.0...
⚠️ GitHub release failed with status: 422
[{"resource":"Release","code":"custom","field":"body","message":"body is too long (maximum is 125000 characters)"}]
retrying... (0 retries remaining)
❌ Too many retries. Aborting...
Error: Too many retries.
```

I would expect the action to truncate the `body` to 125000 characters
