### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by qianbinbin** [softprops/action-gh-release#377]
Hello,

A few days ago my scheduled action failed with `Error: Cannot read properties of undefined (reading 'data')`, for details see https://github.com/qianbinbin/fdroid-priv-ext/actions/runs/5779647317/job/15662229381

It doesn't reproduce for now, and before that the action ran for months smoothly.

My simple script:

```
      - name: Release
        id: release
        if: ${{ steps.create.outputs.VERSION != '' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create.outputs.VERSION }}
          body: ${{ steps.create.outputs.CHANGELOG }}
          files: build/*
```

The full version is [here](https://github.com/qianbinbin/fdroid-priv-ext/blob/10815e12836c27a731c164f342f2a0c776b38c76/.github/workflows/build.yml).

Any help is appreciated.
