### ISSUE TITLE
[Question]Combined zip file generated instead of individual links

### ISSUE THREAD

**Issue by bigcat26** [softprops/action-gh-release#378]
Hi, I've use the plugin to create a release for my github project. I wrote the config as follows:

```yml
      - name: Release assets
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE }}
          tag_name: ${{ env.RELEASE }}
          files: artifact/*.zip
```

There were two zip files in the artifact directory. What I expected was that it would create one download link for each zip file found in the artifact directory. However, only one link was generated, which was a zip file containing all of the original zip files packed together.
