### ISSUE TITLE
Even with "draft: false", drafts get made

### ISSUE THREAD

**Issue by probonopd** [softprops/action-gh-release#379]
I am using this:

```
    - name: Upload Artifacts to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/attrutil
        tag_name: continuous
        target_commitish: ${{ github.sha }}
        draft: false
```

https://github.com/probonopd/attrutil/blob/main/.github/workflows/build.yml

I was hoping that thanks to `draft: false`, the releases would not be created as drafts, but they are.
