### ISSUE TITLE
files path always fails

### ISSUE THREAD

**Issue by machinshin** [softprops/action-gh-release#380]
i'm trying to use this action for releases but `with.files` fails so I'm unclear on what the expected parameters are. 
I get this error:  `Pattern './dist/api.d.ts' does not match any files.`

my typescript build config writes files to `./dist/` , I've tried pathing with and w/o the "./", tried globs like: `dist/**/*.*` but no success. 
as you can see below I've also tried explicitly naming the files (though that shouldn't be necessary). Any help is appreciated

```yaml
     uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGELOG.md
        token: ${{ secrets.GH_TOKEN }}
        tag_name: ${{ env.TAG }}
        name: ${{ env.TAG }}
        files: |
          ./dist/api.d.ts
          ...other-files....
```
