### ISSUE TITLE
Support environment variables and bash expressions in file names

### ISSUE THREAD

**Issue by skyfrk** [softprops/action-gh-release#4]
It would be great to be able to use environment variables and the output of bash expressions like below:

```yml
- name: Prepare GitHub Release
  run: mv some.file some.file-$GITHUB_SHA-$(git describe --tags --exact-match)
- name: Release to GitHub Releases
  uses: docker://softprops/action-gh-release
  if: startsWith(github.ref, 'refs/tags/')
  with:
    files: some.file-$GITHUB_SHA-$(git describe --tags --exact-match)
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by softprops** [comment]
This is a neat idea. At the moment we only support glob matching. You may be able to get part of the way there with [GitHub context variables](https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions#github-context) which get expanded before the are passed to the action I believe 

I haven't tried this myself but something like this may help

```yaml
files: some.file-${{ github.sha }}-*
```

**Comment by tuler** [comment]
If you don't have the exact string you want in a GitHub context variable, you can use a step to create an output with the value you need. Example:

```
- run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//''}
  id: release
- uses: softprops/action-gh-release@v1
  with:
    files: some.file-${{ steps.release.outputs.version }}.tar.gz
    env:
      GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
```

**Comment by softprops** [comment]
That works as too. 

The the files input supports glob patterns so you could just do `some.file-*.tar.gz` as well

**Comment by softprops** [comment]
since there are known alternatives. I'm going to close this issue for now

**Comment by tenzap** [comment]
It would be easier if access to ENV var, as well as to $HOME or ~ was available.

It took me some time to figure out this workaround: put the environment var you need into the `env` context, and the use that.

To put the environment var you need into the `env` context, add this a step of your job:
```
echo "my_home=$HOME" >> $GITHUB_ENV
```
Then in softprops/action-gh-release@v1 step you can use it like this:
```
  with:
    files: ${{ env.my_home }}/aFile
```
Maybe this can help someone.

**Comment by Patrix9999** [comment]
I know that this issue is closed, but nobody's mention that the simplest way to overcome this limitation is to expand the env variable like this:
```yml
env:
  project_name: "secret"
  file_extension: ".txt"
  file_name: $project_name$file_extension

steps:
  - name: Expand env.vars
    run: |
      echo "file_name=${{ env.file_name}}" >> $GITHUB_ENV
```

By default shell variables won't be expanded (they will have a value saved like this: "$project_name$file_extension"), but context variables will work properly, so we need to just use ``${{ env.file_name}}`` after expanding our variable in a step BEFORE running `action-gh-release`.
