### ISSUE TITLE
GitHub error 403 undefined

### ISSUE THREAD

**Issue by CryZe** [softprops/action-gh-release#400]
I'm getting the following error:
```
👩‍🏭 Creating new GitHub release for tag latest...
⚠️ GitHub release failed with status: 403
undefined
retrying... (2 retries remaining)
👩‍🏭 Creating new GitHub release for tag latest...
⚠️ GitHub release failed with status: 403
undefined
retrying... (1 retries remaining)
👩‍🏭 Creating new GitHub release for tag latest...
⚠️ GitHub release failed with status: 403
undefined
retrying... (0 retries remaining)
❌ Too many retries. Aborting...
Error: Too many retries.
```
https://github.com/CryZe/game-maker-auto-splitter/actions/runs/7301685228/job/19899026066#step:5:10

This is how I invoke the action:
```yaml
      - name: Release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          files: target/wasm32-unknown-unknown/release/game_maker_auto_splitter.wasm
          name: Latest
          tag_name: latest
          body: This contains the latest version of the auto splitter.
```

**Comment by estebanfern** [comment]
Same error :(

**Comment by StefH** [comment]
Same here:
![image](https://github.com/softprops/action-gh-release/assets/249938/604455bd-72b7-4435-ae45-d7ab8e21d385)

**Comment by christianll9** [comment]
[Here](https://github.com/softprops/action-gh-release/issues/236#issuecomment-1150530128) is one solution. Or look into one of the other open 403 Error issues in this repo.

**Comment by estebanfern** [comment]
Hey, i found the solution.
In te repository settings, go to Actions -> General
![image](https://github.com/softprops/action-gh-release/assets/54006155/93a613b4-398d-4a28-90c3-7fe297269cd5)
Allow Read and Write Permissions for Github Workflows and save changes.
If your repository is from an organization you will have to do an extra step, go to Organization Settings -> Actions -> General
![image](https://github.com/softprops/action-gh-release/assets/54006155/c09b008d-60a6-4e9a-9444-27e8b94437ca)

**Comment by eggsy84** [comment]
You should also be able to specify that in the job with permissions such as

```
create-release:
    name: Create draft release
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1

# rest of code here
```
