### ISSUE TITLE
Uploading artifacts to existing tag/release

### ISSUE THREAD

**Issue by vitalykarasik** [softprops/action-gh-release#403]
Either I'm missing something basic, or there is a weird bug.
When I'm using this code in my workflow and triggering workflow using 'release create' event, action works nice:

```
      - name: Upload Release assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**
```

But if I'm calling my workflow in another way [i.e. via push event or with workflow_call] and providing tag_name, it fails with "resource":"Release","code":"already_exists","field":"tag_name".

```
       - name: Upload Release assets
         uses: softprops/action-gh-release@v1
         with:
            files: dist/**
            tag_name: 'refs/tags/v0.91.31.00'     
```

 In both cases, Github tag and release already existed before I called my workflow. So why in the first case it worked, and in another case failed? 
 
 Any idea how to explain that?
 Thanks, Vitaly
