### ISSUE TITLE
tag_name missing from with, and so I get "⚠️ GitHub Releases requires a tag" error

### ISSUE THREAD

**Issue by CamJN** [softprops/action-gh-release#408]
I have a workflow that contains:

```
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: pkg/*.zip/*.dmg
        name: ${{ steps.version.ouputs.version }}
        tag_name: ${{ steps.version.ouputs.version }}
```

When it runs I see this in the actions output:

```
Run softprops/action-gh-release@v1
  with:
    files: pkg/*.zip/*.dmg
    token: ***
  env:
    GIT_AUTHOR_NAME: github-actions[bot]
    GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
    GIT_COMMITTER_NAME: github-actions[bot]
    GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
    MACOS_VER_NUM: 14
    CERT_IDENTITY: me
Error: ⚠️ GitHub Releases requires a tag
```

Note that the name and tag_name are missing.

On another workflow I have this:

```
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: getargv.py/dist/*
        name: ${{ steps.bump_version.outputs.new_version }}
        tag_name: ${{ steps.bump_version.outputs.new_version }}
```

and when that runs I get this output:

```
Run softprops/action-gh-release@v1
  with:
    files: getargv.py/dist/*
    name: 0.11
    tag_name: 0.11
    token: ***
  env:
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.12.1/x64
    PKG_CONFIG_PATH: /Users/runner/hostedtoolcache/Python/3.12.1/x64/lib/pkgconfig
    Python_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.12.1/x64
    Python2_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.12.1/x64
    Python3_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.12.1/x64
👩‍🏭 Creating new GitHub release for tag 0.11...
⬆️ Uploading getargv-0.11-cp312-cp312-macosx_12_0_universal2.whl...
⬆️ Uploading getargv-0.11.tar.gz...
🎉 Release ready at https://github.com/getargv/getargv.py/releases/tag/0.11
```

In the non-working workflow I know the `${{ steps.version.ouputs.version }}` value is set as I use it in a previous step.
