### ISSUE TITLE
⚠️ GitHub release failed with status: 422 undefined

### ISSUE THREAD

**Issue by yektasarioglu** [softprops/action-gh-release#429]
Suddenly, I got this 422 undefined error once again.

``` yaml
      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.LATEST_GIT_TAG }}
          generate_release_notes: true
          files: web/backend/build/libs/backend.jar
```

<img width="1310" alt="image" src="https://github.com/softprops/action-gh-release/assets/29422728/db458b98-cfc6-4a2b-8c89-b45c1c0cde63">

Any ideas? Thank you.
