### ISSUE TITLE
GitHub release failed related to file DexMetadata (.dm) in Android with status: Not Found 

### ISSUE THREAD

**Issue by HienLeGcx** [softprops/action-gh-release#434]
When I target to Android SDK 34, creating a release build generates another new file `.dm` [(Details)](https://developer.android.com/topic/performance/baselineprofiles/manually-create-measure#traditional-installation). Although the Github release is successfully created, the action has failed with status `Not Found`. Any ideas how to fix it? Please note that any Github release without `.dm` file always succeeds.

```
     - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: Dev Release ${{ steps.version.outputs.version-name }}
          prerelease: true
          files: "**/app/build/outputs/apk/dev/release/**"
          fail_on_unmatched_files: true
          generate_release_notes: true
```

![Screenshot 2024-04-08 at 16 06 54](https://github.com/softprops/action-gh-release/assets/104769749/4ad27a41-4611-4186-b496-f6a7d070c4dc)

![Screenshot 2024-04-08 at 16 07 35](https://github.com/softprops/action-gh-release/assets/104769749/cb9cafc4-7df8-4fc8-993d-5300fa2e7d9a)
