### ISSUE TITLE
File pattern not matching file name when using "

### ISSUE THREAD

**Issue by JW-CH** [softprops/action-gh-release#440]
### Introduction
I was having issues with the action-gh-release@v2, I found that there were some other issues with `v1` that were fixed in `v2`. I had to spend quite a bit of time to find that `"` is not allowed when having multiple conditions.

### Current configuration

```yml
- name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: |
            "ImmichFrame*"
            "com.immichframe*"
```

### Problem
Following config is not working:
```yml
files: |
    "ImmichFrame*"
    "com.immichframe*"
```

Fix (not use "):
```yml
files: |
    ImmichFrame*
    com.immichframe*
```
