### ISSUE TITLE
files option does not respect working-directory setting

### ISSUE THREAD

**Issue by jerryc05** [softprops/action-gh-release#458]
`files` option does not seem to respect `jobs.<job_name>.defaults.run.working-directory` from github. I have to prepend working directory path to every file under `files` for gh actions to find the correct file.

**Comment by jerryc05** [comment]
here is an excerpt, hope this helps:
```

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm i

      - name: Build
        run: pnpm run dist

      - name: Deploy to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: frontend/dist/*.zip
          tag_name: zipped_dist
```

where `pnpm run dist` command packages everything into a zip file.

If this workflow looks good to you, I can try to provide a minimal reproducible  repo.

**Comment by softprops** [comment]
I think I see the issue

the following settings the working directory for each step. think of it like the PWD path when executing a step

```yml
    defaults:
      run:
        working-directory: ./frontend
```

In your files declaration you provide the pattern`frontend/dist/*.zip` which will be resolved while you are in the `frontend` directory which would assume a path more like `frontend/frontend/dist/*.zip` because its relative to the working-directory for the step. 

```yml
      - name: Deploy to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: frontend/dist/*.zip
```

Could you try and remove the frontend prefix from that step? Since the working-directory is frontend that would then resolve to something like  `frontend/dist/*.zip`

```yml
      - name: Deploy to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
```
