### ISSUE TITLE
File glob does not work with directories

### ISSUE THREAD

**Issue by haata** [softprops/action-gh-release#48]
For example I have the following.

```
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        prerelease: true
        files: |
          'Keyboards/firmware/*.dfu.bin'
          'Bootloader/Builds/bootloader/*.bootloader.bin'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The glob doesn't seem to work correctly.

```
👩‍🏭 Creating new GitHub release for tag v0.5.7test...
🤔 'Keyboards/firmware/*.dfu.bin','Bootloader/Builds/bootloader/*.bootloader.bin' not include valid file.
```

For now I'll get around this by scripting the build to output the files to a single directory (though this is not ideal).

**Comment by haata** [comment]
Aha! No quotes (somewhat confusing).

```
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        prerelease: true
        files: |
          Keyboards/firmware/*.dfu.bin
          Bootloader/Builds/bootloader/*.bootloader.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
