### ISSUE TITLE
Upload fails with Error: write EPIPE

### ISSUE THREAD

**Issue by fingers10** [softprops/action-gh-release#482]
I'm trying to generate release using this actions. But the upload keeps failing with the below error message

**CI:**
```yml
- name: Generate Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/Web/**
          body: "Binaries for Blazor Web App"
          tag_name: ${{ github.ref_name }}
```

**Error:**
```
Error: Not Found
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
Emitted 'error' event on TLSSocket instance at:
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
```

Complete details can be found in https://github.com/ILoveDotNet/ilovedotnet/actions/runs/9967035675/job/27540064386

Please help me on what I'm missing.
