### ISSUE TITLE
Provide option to compress files before upload

### ISSUE THREAD

**Issue by dhcgn** [softprops/action-gh-release#49]
When upload a windows executable the browser and windows is blocking the file. It would be nice, if the action could provide option to compress files before upload.

**Comment by crazy-max** [comment]
@dhcgn You could use the [UPX GitHub Action](https://github.com/crazy-max/ghaction-upx) with a workflow that looks like this:

```yml
name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1
        with:
          version: latest
          file: MyBinary.exe
          args: -fq
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: MyBinary.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
