### ISSUE TITLE
Upload faling on windows-latest with EBUSY

### ISSUE THREAD

**Issue by lostbean** [softprops/action-gh-release#51]
I'm using this action to release binaries from a matrix CI [workflow](https://github.com/arche-tool/arche/runs/683791381) building on macOS, linux and windows. The windows job is failing with the following error:
`EBUSY: resource busy or locked, lstat 'D:\pagefile.sys'`
![image](https://user-images.githubusercontent.com/470077/82230859-b2fb0100-9902-11ea-81bf-385b3b92189e.png)

The other two are working just fine. Is `action-gh-release` supported on a windows build?

**Comment by softprops** [comment]
It looks like you are trying to include all files at the root of your file system with`/*`. This is likely not what you want. You could try a relative path. This should be relative to the working directory of  your checkout.

**Comment by lostbean** [comment]
Thanks for sharing this awesome GH Action @softprops!

Oh that is definitely not what I want. The workflow is defined exactly like this:
```
    - name: Setup env
      run: |
        echo ::set-env name=OUTPUT_DIR::$(make show-output-dir)
    - name: Release cli
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.OUTPUT_DIR }}/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
Where `OUTPUT_DIR` is the relative path of the output folder. This exact workflow works on macOS and linux. Maybe something related to the use of environment variables being broken in the Windows setup. It seems the variable was properly set:
![image](https://user-images.githubusercontent.com/470077/82378299-431c7180-99fb-11ea-9c62-4d0c1c1405ce.png)

Could it be the env is not being passed down to the action code? I'm not sure at which point the context `${{ env.OUTPUT_DIR }}` is resolved.

**Comment by softprops** [comment]
> Could it be the env is not being passed down to the action code?

That would be my theory. I don't think env gets inherited between steps by default

I'd try some experiments like setting it explicitly

Or adding a debug step in between

```yaml
with:
        files: ${{ env.OUTPUT_DIR }}/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       OUTPUT_DIR: ${{ env.OUTPUT_DIR }}
```
