### ISSUE TITLE
Append Body feature not working(or i dont know how)

### ISSUE THREAD

**Issue by CraftyRyte** [softprops/action-gh-release#527]
Hi. i was trying to use append body feature to append a certain text to my body file. it doesnt work.
heres my code:

```yaml
name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
            github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            changelog_increment_filename: body.md
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          append_body: true
          body_path: "body.md"
          body: |
            ## Install the library! 
            PyPi page: https://pypi.org/project/pygess-py/
            Install using: `pip install pygess-py` (on Windows) `pip3 install pygess-py` (on Mac)"
          tag_name: ${{ env.REVISION }}
          name: "Release ${{ env.REVISION }}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}```

**Comment by pat-johnson-dev** [comment]
FWIW, I got this working using the following:
``` YAML
      - name: update-release-notes
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.release_tag }}
          append_body: true
          generate_release_notes: false
          body: |
            - ✅ This is my body text!
```

Worth noting that I already had a release created in a previous step where the notes are done manually, not using `generate_release_notes: true`
