### ISSUE TITLE
Help with config file

### ISSUE THREAD

**Issue by Denzy7** [softprops/action-gh-release#530]
I'm using 
```
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: false
        files: out-${{ matrix.os }}/**
        prerelease: false
```

and run this
```
git push origin main
git push --tags
```
but the release is not created

`out-${{ matrix.os }}/**` is a directory containing `cmake --install` output

[Whole file](https://github.com/Denzy7/test-ci/blob/c50b13207eb2e0f4f193c30b4e14b20627f82c58/.github/workflows/cmake-multi-platform.yml)

[edit]
workflow file is running on multiple platforms, will that be an issue?
