### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by fxzxmicah** [softprops/action-gh-release#531]
```
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: <name>
        body_path: release.log
        files: RPMS/*
```
```
🤔 Pattern 'RPMS/*' does not match any files.
👩‍🏭 Creating new GitHub release for tag 6.11.4-201.fc40...
🤔 RPMS/* not include valid file.
```
What I can confirm is that the RPMS directory is not empty.
