### ISSUE TITLE
Error: other side closed

### ISSUE THREAD

**Issue by iliapnmrv** [softprops/action-gh-release#536]
```yml
Run softprops/action-gh-release@v2
  with:
    tag_name: v2.5.1
    body_path: distribution/whatsnew/whatsnew-ru-RU
    files: android/app/build/outputs/apk/release/apk-v2.5.1-release.apk
 
👩‍🏭 Creating new GitHub release for tag v2.5.1...
⬆️ Uploading apk-v2.5.1-release.apk...
Error: other side closed
```
I have release `v2.5.1-rc.0`, then I want to create stable release `v2.5.1`
My release gets created in GitHub releases (without artifact) but pipeline fails with `Error: other side closed`

Do you have any ideas?
