### ISSUE TITLE
Use `target_commitish` along with `repository`?

### ISSUE THREAD

**Issue by n8marti** [softprops/action-gh-release#546]
Maybe I'm misunderstanding how this is supposed to work, but I'd like for a release created in another repo using the `repository` input to use the hash from the source repo, but it seems to only accept values from the `repository` repo:

From workflow in `FaithLife-Community/LogosLinuxInstaller`:
```
jobs:
  build:
    uses: ./.github/workflows/build-branch.yml
    with:
      branch: main

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build.outputs.bin_name }}
    - name: Run shell tasks
      run: |
        find -name oudedetai -type f -exec chmod +x {} \;
    - name: Upload release to test repo
      uses: softprops/action-gh-release@v1
      with:
        tag_name: main-latest
        target_commitish: ${{ needs.build.outputs.sha }}
        body: ''
        prerelease: true
        files: ${{ needs.build.outputs.bin_name }}
        repository: FaithLife-Community/test-builds
        token: -----
```
GHA output:
```
Run softprops/action-gh-release@v1
Updating commit from "main" to "319cffc48f9291a5f71386fedc3776e846cfb168"
⚠️ Unexpected error fetching GitHub release for tag refs/heads/main: HttpError: Validation Failed: {"resource":"Release","code":"invalid","field":"target_commitish"}
Error: Validation Failed: {"resource":"Release","code":"invalid","field":"target_commitish"}
```
I assume it's failing because the validation is checking against hashes in the `repository` repo rather than the workflow repo.
