### ISSUE TITLE
'Error: Headers Timeout Error' when releasing

### ISSUE THREAD

**Issue by Michael-Gunther-KPM** [softprops/action-gh-release#549]
This is a new error in version 2. Files are uploaded and released fine, but the action fails with the above error-> i.e. everything works fine but I get an error anyway that I'd like to not be there 

Of note:
- Occurs in only one repository
- Files uploaded are large 0.8 GB and 1.7 GB for the first two files
- Uploaded to a GitHub enterprise
- Same code works in V1

Code used:
```
- name: Release  
      uses: softprops/action-gh-release@v2  
      id: create_release  
      with:  
        draft: false  
        prerelease: false
        tag_name: measura-v${{inputs.version}}
        # body_path: CHANGELOG.md
        token: ${{ secrets.RELEASE_TOKEN }}
        files: |
          ./out/measura_core_installer_${{inputs.version}}.exe
          ./out/measura_suite_installer_${{inputs.version}}.exe
          ./measura-guid.json
```
