### ISSUE TITLE
Request body length mismatch after v2.2.0

### ISSUE THREAD

**Issue by dysonfrost** [softprops/action-gh-release#555]
The latest release ([v2.2.0](https://github.com/softprops/action-gh-release/releases/tag/v2.2.0)) introduced a bug that causes the action to fail with the error: `Error: Request body length does not match content-length header`.

This error occurs in our workflow when uploading assets to a release. This issue was not present in prior versions of the action.

### Steps to reproduce:

1. Set up a GitHub Actions workflow with the following snippet:
```yml
- name: Upload Asset
  uses: softprops/action-gh-release@master
  with:
    target_commitish: ${{ inputs.sha }}
    tag_name: ${{ inputs.name }}
    files: ./path/to/assets.zip
    append_body: true
    body: |-
      ### Artifacts
      * `Release asset` - assets.zip
```
2. Trigger the workflow with the appropriate inputs.

### Expected Behavior:
The workflow completes successfully, and the asset (assets.zip) is uploaded to the GitHub release with the specified body content.

### Actual Behavior:
The workflow fails with the following error:
`Error: Request body length does not match content-length header`

### GHA Output:
```
Run softprops/action-gh-release@master
Found release *** (with id=190203584)
⬆️ Uploading assets.zip...
Error: Request body length does not match content-length header
```
