### ISSUE TITLE
Error: Request body length does not match content-length header

### ISSUE THREAD

**Issue by qwerttvv** [softprops/action-gh-release#556]
```
    - name: Upload firmware to release
      uses: softprops/action-gh-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
```
full yml
`https://github.com/qwerttvv/Router/blob/master/.github/workflows/M2-VIKINGYFY.yml`

log
```
👩‍🏭 Creating new GitHub release for tag 2024.12.11-22.51_M2-VIKINGYFY...
⬆️ Uploading version.buildinfo...
⬆️ Uploading sha256sums...
⬆️ Uploading profiles.json...
⬆️ Uploading immortalwrt-qualcommax-ipq60xx-cmiot_ax18.manifest...
⬆️ Uploading immortalwrt-qualcommax-ipq60xx-cmiot_ax18-squashfs-sysupgrade.bin...
⬆️ Uploading immortalwrt-qualcommax-ipq60xx-cmiot_ax18-squashfs-factory.ubi...
⬆️ Uploading immortalwrt-qualcommax-ipq60xx-cmiot_ax18-initramfs-uImage.itb...
⬆️ Uploading feeds.buildinfo...
⬆️ Uploading config.buildinfo...
Error: Request body length does not match content-length header
```

good ver-last week
https://github.com/softprops/action-gh-release/tree/92bc83c4214f780e84c7d2a85464a2ca05ebc2f0

not good ver-now`softprops/action-gh-release@master`
https://github.com/softprops/action-gh-release/tree/7b4da11513bf3f43f9999e90eabced41ab8bb048
