### ISSUE TITLE
Cannot disable release body append mechanism when updating an existing release

### ISSUE THREAD

**Issue by matusnovak** [softprops/action-gh-release#57]
If you update the release from multiple jobs then the **body is appended and the behavior cannot be controlled**. Here is where the problem is: https://github.com/softprops/action-gh-release/blob/master/src/github.ts#L171

Why is this a problem?

Some projects need to be built on multiple architectures and multiple operating systems. For example, compile on x64-windows, x86-windows, x64-linux, x64-osx. Such project is run on 4 different jobs, uses a matrix configuration -> each job creates a release with a unique artifact. 

What I want to accomplish is to have a single release with multiple binaries for the same architecture with git log as the body of the release. But instead I get this:

![image](https://user-images.githubusercontent.com/10331278/86516089-13e08900-be1e-11ea-8907-d9b2a040658b.png)

My config looks like this:

```yml
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{ steps.create_changelog.outputs.log }} # comes from "git log"
          files: ${{ steps.create_artifact.outputs.path }}
          draft: false
          prerelease: false
          name: Release ${{ steps.get_release_name.outputs.tag }}
          tag_name: ${{ steps.get_release_name.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Would it be possible to implement something like this?

```yml
with:
  append: false
```
