### ISSUE TITLE
`files` option should be a list

### ISSUE THREAD

**Issue by khatchad** [softprops/action-gh-release#570]
I see the description of the `files` option as follows:

Name | Type | Description
-- | -- | --
files | String | Newline-delimited globs of paths to assets to upload for release

For multiple files, it's used as follows:

```yml
with:
  files: |
    Release.txt
    LICENSE
```

Why not make it a list?

```yml
with:
  files:
    - Release.txt
    - LICENSE
```
