### ISSUE TITLE
HELP: Action failing to publish release asset with: `Error: Resource not accessible by integration`

### ISSUE THREAD

**Issue by jim-junior** [softprops/action-gh-release#572]
I am trying to use this action to publish a release asset but it fails with this error

```
Found release 0.0.3 (with id=193949952)
⚠️ Unexpected error fetching GitHub release for tag refs/tags/0.0.3: HttpError: Resource not accessible by integration - https://docs.github.com/rest/releases/releases#update-a-release
Error: Resource not accessible by integration - https://docs.github.com/rest/releases/releases#update-a-release
```

I have used an exact copy of the workflow file before and it has been working but today i tried and it failed to run.

I have no idea why the error is occurring

To rebuild the error:
- Repository: [https://github.com/jim-junior/eda](https://github.com/jim-junior/eda)
- Workflow File: [https://github.com/jim-junior/eda/blob/main/.github/workflows/build.yml](https://github.com/jim-junior/eda/blob/main/.github/workflows/build.yml)
- Failing Action: [https://github.com/jim-junior/eda/actions/runs/12694376957/job/35384018948](https://github.com/jim-junior/eda/actions/runs/12694376957/job/35384018948)

**Comment by Julienraptor01** [comment]
i got the same exact issue
maybe GitHub has change the default permissions of the default token ?
https://github.com/Julienraptor01/planeteerunstucker/actions/runs/12728727134/job/35479659229

**Comment by jim-junior** [comment]
> i got the same exact issue maybe GitHub has change the default permissions of the default token ? https://github.com/Julienraptor01/planeteerunstucker/actions/runs/12728727134/job/35479659229

That is most likely the reason, changed my token with a new custom one and it worked. 
Its actually stated in the [GitHub Docs](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#update-a-release)

**Comment by spamegg1** [comment]
I have the same issue.

- I have `permissions: contents: write` set, 
- I also have the new "Read repository contents and packages permissions" set in the new Workflow Settings... 
- but I still get the same error!

Here's the workflow file:

```yml
name: Release LaTeX document and source
on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          root_file: Epp.tex
          latexmk_shell_escape: true
      - name: Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: "v1.0.${{ github.run_number }}"
          make_latest: true
          generate_release_notes: true
          preserve_order: true
          files: src/Epp.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
It's funny because
- it works if I close a pull request *that I made myself*, but 
- it doesn't work if I close a pull request *made by someone else.*
