### ISSUE TITLE
Failed with 404 "discussion category unmatch"

### ISSUE THREAD

**Issue by harrymkt** [softprops/action-gh-release#573]
Code:
```yaml
- name: Release
  uses: softprops/action-gh-release@v2
  with:
    files: |
      file1
      file2
    draft: false
```

As you can see, I'm not even using `discussion_category_name` input.
