### ISSUE TITLE
release published trigger

### ISSUE THREAD

**Issue by tcurdt** [softprops/action-gh-release#59]
I want to trigger another workflow when the release has been published

```
on:
  release:
    types: [published]
```

Looking [at the code](https://github.com/softprops/action-gh-release/blob/master/src/main.ts#L46) I am not sure, but it looks like this might cause a race condition with the file upload.

Does the release maybe have to be drafted, files uploaded and then published for this to work?
I could not find clear documentation on this.

**Comment by tcurdt** [comment]
ATM I wish for a race condition :-D

Right now it's not triggering other workflows at all for me.
Is that a known issue?

**Comment by tcurdt** [comment]
It only triggers when the Personal Access Token is used instead of the standard Github Token.

**Comment by TheBestMoshe** [comment]
This might help someone

https://stackoverflow.com/a/60418414/9642772

**Comment by minhdanh** [comment]
For anyone looking to trigger another workflow with release.published event:
- Try to create a new Personal Access Token with just `workflow` permission
- Then in your workflow:
```
- name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
```
