### ISSUE TITLE
Option to upload glob assets in reverse order

### ISSUE THREAD

**Issue by Tremeschin** [softprops/action-gh-release#609]
Hi, would it be possible to have a `reverse: bool` flag for globs?

I need to [compile a project](https://github.com/Tremeschin/nVibrant/releases/tag/v1.0.1) against all nvidia [driver versions](https://github.com/NVIDIA/open-gpu-kernel-modules/tags) (as internal structs can change over time), but the upload order is slightly inconvenient to grab the latest files as they are sorted in numerical order, e.g.:

```
nvibrant-v515.86.01-v1.0.1.bin
nvibrant-v520.56.06-v1.0.1.bin
nvibrant-v520.61.05-v1.0.1.bin
nvibrant-v520.61.07-v1.0.1.bin
nvibrant-v525.105.17-v1.0.1.bin 
...
nvibrant-v570.133.07-v1.0.1.bin
nvibrant-v570.86.15-v1.0.1.bin
```

If not, how could I achieve it? Was thinking on doing something like this, but haven't tested:

```yaml
- name: Reverse files
  id: reverse_files
  run: echo "files=$(ls -1 release/ | sort -r)" >> "$GITHUB_OUTPUT"

- name: Create release
  uses: softprops/action-gh-release@v2
  with:
    name: Release v${{env.GHA_VERSION}}
    tag_name: v${{env.GHA_VERSION}}
    files: ${{steps.reverse_files.outputs.files}}
```

Bit of an unconventional situation, I know 😅 

Thanks!
