### ISSUE TITLE
Appending release note now fail

### ISSUE THREAD

**Issue by RadxaYuntian** [softprops/action-gh-release#613]
2 weeks ago the action was working: https://github.com/radxa-pkg/radxa-overlays/actions/runs/14512172143/job/40713439773
Now with the same input it will fail: https://github.com/radxa-pkg/edk2-cix/actions/runs/14699628860/job/41246948535

**Comment by RadxaYuntian** [comment]
Both uses the following snippet:

```yaml
    - name: "Append changelog"
      uses: "softprops/action-gh-release@v2"
      with:
        append_body: true
        body: |
          ## Changelog for ${{ env.version }}
          ${{ env.changes }}
        tag_name: "${{ env.version }}"
```
