### ISSUE TITLE
v2.3.0 failed

### ISSUE THREAD

**Issue by qwerttvv** [softprops/action-gh-release#627]
https://github.com/softprops/action-gh-release/tree/d5382d3e6f2fa7bd53cb749d33091853d4985daf

Ubuntu 24.04.2
Version: 20250602.3.0
https://github.com/actions/runner-images/blob/ubuntu24/20250602.3/images/ubuntu/Ubuntu2404-Readme.md

```
    - name: Release
      uses: softprops/action-gh-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.tag }}
        files: |
          cdnspeedtest-linux-arm64.tar.xz
        body_path: ${{ github.workspace }}-nightly_builds_release_notes.txt
```

```
Run softprops/action-gh-release@master
👩‍🏭 Creating new GitHub release for tag 2025.06.10-09.14_cdnspeedtest...
⬆️ Uploading cdnspeedtest-linux-arm64.tar.xz...
  #  /home/runner/runners/2.325.0/externals/node20/bin/node[11847]: v8::MaybeLocal<v8::Promise> node::fs::FileHandle::ClosePromise() at ../src/node_file.cc:457
  #  Assertion failed: !closed_
----- Native stack trace -----
 1: 0xcc7f77 node::Assert(node::AssertionInfo const&) [/home/runner/runners/2.325.0/externals/node20/bin/node]
 2: 0xcd24fa node::fs::FileHandle::ClosePromise() [/home/runner/runners/2.325.0/externals/node20/bin/node]
 3: 0xcd2666 node::fs::FileHandle::Close(v8::FunctionCallbackInfo<v8::Value> const&) [/home/runner/runners/2.325.0/externals/node20/bin/node]
 4: 0xf6c56f v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/home/runner/runners/2.325.0/externals/node20/bin/node]
 5: 0xf6cddd  [/home/runner/runners/2.325.0/externals/node20/bin/node]
 6: 0xf6d2a5 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/home/runner/runners/2.325.0/externals/node20/bin/node]
 7: 0x1977df6  [/home/runner/runners/2.325.0/externals/node20/bin/node]
----- JavaScript stack trace -----
1: close (node:internal/fs/promises:250:23)
2: upload (/home/runner/work/_actions/softprops/action-gh-release/master/dist/index.js:[16](https://github.com/qwerttvv/Router/actions/runs/15548228958/job/43773741086#step:10:17):16275)
```
