### ISSUE TITLE
[FEATURE] Add the ability to set release name

### ISSUE THREAD

**Issue by Amet13** [softprops/action-gh-release#7]
Hi.
Thanks for a plugin, it works like a charm.

I've successfully migrated my project from TravisCI to GitHub Actions with your plugin.
TravisCI have [option](https://docs.travis-ci.com/user/deployment/releases/#advanced-options) for setting release name.
I've used it in [my pipeline](https://github.com/Amet13/master-thesis/blob/master/.travis.yml#L17) and got a release with human-readable name, [e.g.](https://github.com/Amet13/master-thesis/releases/tag/untagged-fd59c8790d6e4d0e9fee)

I didn't find such an option in your plugin but I hope it's possible to realize in GitHub Actions,
[Here](https://github.com/Amet13/master-thesis/releases/tag/untagged-6ae140104dc3a01262ba) is a tag deployed with you plugin.

Thank you.

**Comment by softprops** [comment]
Awesome! I love getting feedback.

You should actually be able to do this today with the name input.

```yaml
with:
  name: awesome release
```

Let me know if that helps

**Comment by AmetPreply** [comment]
Wow, thanks. I'll check it today.
Sorry, it's my bad, didn't read the documentation.

**Comment by softprops** [comment]
no worries. That's for the feedback. Quick heads up. I'll soon be pushing a new version of the action  with better cross platform support. At the moment docker:// actions can only run on linux virtual hosts. 

The notable change should just be removing the `docker://` part of the `uses:` yaml field. All other functionality should remain the same

**Comment by shinebayar-g** [comment]
@softprops Hi. How can I change release name to something like this?

**Release 0.1.5** include a word *Release* in front of tag name?

I  tried to pass it as env like these, but didn't work.

```yml
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          name: Release $RELEASE_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_NAME: ${GITHUB_REF#refs/tags/}
```

```yml
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          name: Release ${GITHUB_REF#refs/tags/}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
