### ISSUE TITLE
Warning: Unexpected input(s) 'repository', valid inputs are ['body', 'body_path', 'name', 'tag_name', 'draft', 'prerelease', 'files']

### ISSUE THREAD

**Issue by guanpengchn** [softprops/action-gh-release#72]
when I use like this

```
- name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repository: guanpengchn/aaa
          files: "dist/**"
```

got a warning and still use the old repo

```
Warning: Unexpected input(s) 'repository', valid inputs are ['body', 'body_path', 'name', 'tag_name', 'draft', 'prerelease', 'files']
```
