### ISSUE TITLE
not include valid file

### ISSUE THREAD

**Issue by black7375** [softprops/action-gh-release#82]
I am trying to upload the released file using this action.

- File: https://github.com/black7375/tealdeer/blob/master/.github/workflows/release.yml
- Release: https://github.com/black7375/tealdeer/releases/tag/v1.4.1-workflow
- Action: https://github.com/black7375/tealdeer/actions/runs/641637088

`Completions` and `Licenses` have been uploaded
![image](https://user-images.githubusercontent.com/25581533/110736974-79460e80-8224-11eb-9226-35c192af4de8.png)

The problem is the built file.
After uploading to artifact, I checked that the download was successful, but the following error occurs.
```
🤔 tldr-linux-x86_64-musl not include valid file.
```
![image](https://user-images.githubusercontent.com/25581533/110737319-10ab6180-8225-11eb-95b7-779937e5eb11.png)

![image](https://user-images.githubusercontent.com/25581533/110737252-efe30c00-8224-11eb-8c96-631a0f4f28b8.png)

Have I missed anything?

**Comment by bdashore3** [comment]
I am also having this issue with uploading a MacOS .app file. It works just fine with .deb and .exe

**Comment by yin1999** [comment]
You have passed a `Dir` to `files`, and it's unable to be uploaded.
![image](https://user-images.githubusercontent.com/15844309/111908002-7e138980-8a92-11eb-88f2-9e649883a25d.png)

You should use a `path` that contains `wildcard characters`,if you want to upload the files contained in the folder.

Examples:

    files: 'path/to/files/*'
    
    files: 'path/to/files/**/*.js'

**Comment by black7375** [comment]
As you advised, I will download it to a specific directory and try to upload it.

But I'm little confused because `completions_` set up in the same way works well.
The files were not inside the any folder, they were located in the working directory.
```yaml
      - uses: softprops/action-gh-release@v1 # actions/create-release, actions/upload-release-asset is deprecated
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            completions_${{ matrix.target }}
```
