### ISSUE TITLE
Release asset download URLs are broken (error 404)

### ISSUE THREAD

**Issue by TheSlowGrowth** [softprops/action-gh-release#86]
I created a draft release via the action-gh-release.
As long as the release is still a draft, I can download the asset that were uploaded from the action-gh-release.
As soon as I publish the release, the download links are all broken, leading to 404 errors.

This is an example of such a broken link:
https://github.com/TheSlowGrowth/Wunderkiste/releases/download/refs%2Ftags%2Fv0.3/Wunderkiste.bin
This release was created with the script like this:
````
- name: Create Release Draft
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            ./firmware/build/Wunderkiste/Wunderkiste.hex
            ./firmware/build/Wunderkiste/Wunderkiste.bin
            ./PCB_Files.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
````
I noticed that the broken download link contains `%2F` characters which the draft-release didn't contain. They may be the reason for the 404. This is what a download link looks like BEFORE releasing the draft: 
https://github.com/TheSlowGrowth/Wunderkiste/releases/download/untagged-[someCharacters]/Wunderkiste.bin

Making a release manually and uploading the files manually creates links that look different, like this: 
https://github.com/TheSlowGrowth/Wunderkiste/releases/download/v0.3/Wunderkiste.bin

It seems to me as if the action-gh-release would internally use `${GITHUB_REF}` to generate the various URLs/asset names. Maybe the "/refs/tags/" string needs to be sanitized?

**Comment by TheSlowGrowth** [comment]
Here's a workaround I found:
If I manually remove the `/refs/tags/` from both the `name` and the `tag_name` argument, it creates links that work just fine.
````
- name: Get release name
        id: getReleaseName
        run: echo ::set-output name=RELEASE_NAME::${GITHUB_REF/refs\/tags\//}

[...]

 - name: Create Release Draft
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ steps.getReleaseName.outputs.RELEASE_NAME }}
          name: Release ${{ steps.getReleaseName.outputs.RELEASE_NAME }}
````

**Comment by softprops** [comment]
believe this was fixed in https://github.com/softprops/action-gh-release/pull/88 . feel free to reopen the issue if it did not

**Comment by XanatosX** [comment]
```yml
       - name: Get release name
         id: getReleaseName
         run: echo ::set-output name=RELEASE_NAME::${GITHUB_REF/refs\/tags\//}
       - name: Create last unstable Release
         uses: softprops/action-gh-release@v1
         with:
           name: Latest unstable
           body: This is the latest unstable build version, feel free to test it out. Most of the time only the windows build got tested!
           tag_name: ${{ steps.getReleaseName.outputs.RELEASE_NAME }}-${{ GITHUB.RUN_NUMBER }}
           draft: false
           prerelease: true
           files: releases/**.zip
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
```

I do try to upload a build like that but I do get the same error as the inital creator. Now my problem this pipeline runs as soon as as someting is getting pushed to the develop branch. 

This should provide some "latest builds" so the tag will be `/refs/tags/develop-{Runner number}`. But this leads to the 404 error if the build is not in draft :( Is there something wrong with my usage of the script?
