### ISSUE TITLE
[question] token/key/pat requirement for separate repo?

### ISSUE THREAD

**Issue by nerdCopter** [softprops/action-gh-release#98]
im confused about tokens/pats/secrets required for separate repo.
(where exactly to create within and organization or the org's repos)

i want to use:
```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: my_gh_org/my_gh_repo
```
where my action is triggered in repo A, but i want my draft release in repo B (i.e. a "nightly").
This is an organization, so i dont have use of PAT, afaik.  need action working for anyone triggering.

**Comment by softprops** [comment]
Hi there. By default a runs secrets.GITHUB_TOKEN is scoped to the repo its run is in. To create releases in other repos you'll need to generate a custom personal access token (typically with a repo permissions) [in your account settings](https://github.com/settings/tokens) create a repo secret for that value to that it can be securely dereferenced in your workflow and provide that secret in our workflow

```yaml
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: my_gh_org/my_gh_repo
```

I'll make a note to update the README example to highlight this
